Repository sensu/sensu-go, pull requests merged in 2018-09, with the labels that each got.

#2020 Remove race flag from build.sh integration tests
  backend/backend_test.go
  build.sh
Labels: ready-for-review

#2017 Separate system info collection from getAgentEntity()
  CHANGELOG.md
  agent/agent.go
  agent/entity.go
  agent/entity_test.go
Labels: ready-for-review

#2000 [Web UI] Create AppLayout component
  dashboard/src/components/AppBar.js
  dashboard/src/components/AppContent.js
  dashboard/src/components/AppFrame.js
  dashboard/src/components/AppLayout/AppLayout.js
  dashboard/src/components/AppLayout/Context.js
  dashboard/src/components/AppLayout/MobileFullWidthContent.js
  dashboard/src/components/AppLayout/index.js
  dashboard/src/components/AppWrapper.js
  dashboard/src/components/Content/Content.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsContainer.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsContainer.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/ListHeader/ListHeader.js
  dashboard/src/components/partials/ListToolbar.js
  dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/EnvironmentView/SilencesContent.js
Labels: ready-for-review, web-ui

#2028 Fix a bug in nagios perfdata parsing
  CHANGELOG.md
  agent/transformers/nagios.go
  agent/transformers/nagios_test.go
Labels: ready-for-review

#1998 Etcd alarms
  CHANGELOG.md
  backend/apid/actions/health.go
  backend/apid/routers/status.go
  backend/apid/routers/status_test.go
  backend/store/etcd/health_store.go
  backend/store/etcd/health_store_test.go
  backend/store/store.go
  cli/client/health.go
  cli/client/interface.go
  cli/client/testing/mock_health_client.go
  cli/commands/cluster/health.go
  cli/commands/cluster/health_test.go
  testing/mockstore/health.go
  types/health.go
  types/status_map.go
Labels: ready-for-review

#2030 Fix a bug in sensuctl check update.
  CHANGELOG.md
  cli/commands/check/interactive.go
Labels: ready-for-review

#2034 Resolve some etcd configuration and operation issues
  CHANGELOG.md
  backend/backend.go
  backend/etcd/etcd.go
  backend/etcd/testing.go
  backend/store/etcd/testutil/store.go
Labels: ready-for-review

#2024 Rewrite/redesign asset implementation
  asset/asset.go
  asset/boltdb_manager.go
  asset/boltdb_manager_test.go
  asset/expander.go
  asset/expander_test.go
  asset/fetcher.go
  asset/fetcher_test.go
  asset/fixtures/LICENSE
  asset/fixtures/invalid-archive.tar
  asset/fixtures/invalid.tar
  asset/fixtures/rubby-on-rails.tar
  asset/fixtures/rubby-on-rails.tar.sha512
  asset/fixtures/rubby-on-rails.tgz
  asset/fixtures/rubby-on-rails.tgz.sha512
  asset/fixtures/unsupported.zip
  asset/integration_test.go
  asset/verifier.go
  asset/verifier_test.go
  vendor/github.com/boltdb/bolt/LICENSE
  vendor/github.com/boltdb/bolt/Makefile
  vendor/github.com/boltdb/bolt/README.md
  vendor/github.com/boltdb/bolt/appveyor.yml
  vendor/github.com/boltdb/bolt/bolt_386.go
  vendor/github.com/boltdb/bolt/bolt_amd64.go
  vendor/github.com/boltdb/bolt/bolt_arm.go
  vendor/github.com/boltdb/bolt/bolt_arm64.go
  vendor/github.com/boltdb/bolt/bolt_linux.go
  vendor/github.com/boltdb/bolt/bolt_openbsd.go
  vendor/github.com/boltdb/bolt/bolt_ppc.go
  vendor/github.com/boltdb/bolt/bolt_ppc64.go
  vendor/github.com/boltdb/bolt/bolt_ppc64le.go
  vendor/github.com/boltdb/bolt/bolt_s390x.go
  vendor/github.com/boltdb/bolt/bolt_unix.go
  vendor/github.com/boltdb/bolt/bolt_unix_solaris.go
  vendor/github.com/boltdb/bolt/bolt_windows.go
  vendor/github.com/boltdb/bolt/boltsync_unix.go
  vendor/github.com/boltdb/bolt/bucket.go
  vendor/github.com/boltdb/bolt/bucket_test.go
  vendor/github.com/boltdb/bolt/cursor.go
  vendor/github.com/boltdb/bolt/cursor_test.go
  vendor/github.com/boltdb/bolt/db.go
  vendor/github.com/boltdb/bolt/db_test.go
  vendor/github.com/boltdb/bolt/doc.go
  vendor/github.com/boltdb/bolt/errors.go
  vendor/github.com/boltdb/bolt/freelist.go
  vendor/github.com/boltdb/bolt/freelist_test.go
  vendor/github.com/boltdb/bolt/node.go
  vendor/github.com/boltdb/bolt/node_test.go
  vendor/github.com/boltdb/bolt/page.go
  vendor/github.com/boltdb/bolt/page_test.go
  vendor/github.com/boltdb/bolt/quick_test.go
  vendor/github.com/boltdb/bolt/simulation_test.go
  vendor/github.com/boltdb/bolt/tx.go
  vendor/github.com/boltdb/bolt/tx_test.go
  vendor/vendor.json
Labels: ready-for-review

#2035 Refactor and tests in agent package
  Gopkg.lock
  Gopkg.toml
  agent/agent.go
  agent/agent_test.go
  agent/timeproxy_test.go
  vendor/github.com/echlebek/crock/time.go
  vendor/github.com/echlebek/crock/timer.go
Labels: ready-for-review, technical-debt, testing

#2043 Add agent id validation
  CHANGELOG.md
  agent/agent.go
  agent/agent_test.go
Labels: ready-for-review

#2046 Moved the sensu-agent binary to ./cmd/sensu-agent.
  CHANGELOG.md
  build.ps1
  build.sh
  cmd/sensu-agent/LICENSE
  cmd/sensu-agent/main.go
  cmd/sensu-agent/start.go
Labels: ready-for-review

#2047 Disable auto text wrapping in sensuctl
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  cli/elements/table/standard.go
  vendor/github.com/boltdb/bolt/.gitignore
  vendor/github.com/boltdb/bolt/bucket_test.go
  vendor/github.com/boltdb/bolt/cursor_test.go
  vendor/github.com/boltdb/bolt/db_test.go
  vendor/github.com/boltdb/bolt/freelist_test.go
  vendor/github.com/boltdb/bolt/node_test.go
  vendor/github.com/boltdb/bolt/page_test.go
  vendor/github.com/boltdb/bolt/quick_test.go
  vendor/github.com/boltdb/bolt/simulation_test.go
  vendor/github.com/boltdb/bolt/tx_test.go
  vendor/github.com/olekukonko/tablewriter/.gitignore
  vendor/github.com/olekukonko/tablewriter/README.md
  vendor/github.com/olekukonko/tablewriter/table.go
  vendor/github.com/olekukonko/tablewriter/test.csv
  vendor/github.com/olekukonko/tablewriter/test_info.csv
  vendor/github.com/olekukonko/tablewriter/util.go
  vendor/github.com/olekukonko/tablewriter/wrap.go
  vendor/vendor.json
Labels: ready-for-review

#2050 Add some helpers to docker cluster configuration
  docker-compose.yaml
Labels: ready-for-review

#2045 Remove KeepaliveTimeout from entities
  CHANGELOG.md
  agent/agent.go
  agent/entity.go
  backend/keepalived/deregisterer.go
  backend/keepalived/integration_test.go
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
  benchmark/cmd/main.go
  cmd/sensu-agent/start.go
  types/entity.go
  types/entity.pb.go
  types/entity.proto
  types/keepalive.go
  types/typemap.go
Labels: ready-for-review

#1976 [Web UI] Refresh tokens when GraphQL request produces 401
  dashboard/src/apollo/authLink.js
  dashboard/src/apollo/resolvers/auth.js
  dashboard/src/apollo/schema/client.graphql
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/components/partials/SigninDialog/SigninDialog.js
  dashboard/src/components/util/DefaultRedirect.js
  dashboard/src/components/util/LastEnvironmentRedirect.js
  dashboard/src/components/util/UnauthenticatedRoute.js
  dashboard/src/mutations/flagTokens.js
Labels: bug, ready-for-review, web-ui

#2060 sensuctl cluster health response contains string representation of error
  CHANGELOG.md
  backend/apid/routers/status_test.go
  backend/store/etcd/health_store.go
  backend/store/etcd/health_store_test.go
  cli/commands/cluster/health_test.go
  types/health.go
Labels: ready-for-review

#2037 Support using sensu-backend with external etcd instances
  CHANGELOG.md
  backend/backend.go
  backend/cmd/start.go
  backend/config.go
  backend/etcd/etcd.go
  backend/etcd/id.go
  backend/etcd/id_test.go
  backend/queue/queue.go
  backend/queue/queue_test.go
Labels: ready-for-review

#2059 Clarify the fork/clone procedure.
  CONTRIBUTING.md
Labels: ready-for-review

#2066 Deprecate Status() and /info
  CHANGELOG.md
  backend/agentd/agentd.go
  backend/apid/actions/health.go
  backend/apid/actions/health_test.go
  backend/apid/apid.go
  backend/apid/routers/health.go
  backend/apid/routers/health_test.go
  backend/apid/routers/status.go
  backend/apid/routers/status_test.go
  backend/backend.go
  backend/daemon/daemon.go
  backend/dashboardd/dashboardd.go
  backend/eventd/eventd.go
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
  backend/messaging/wizard_bus.go
  backend/pipelined/pipelined.go
  backend/schedulerd/schedulerd.go
  types/health.go
  types/status_map.go
Labels: ready-for-review

#2068 Remove staging resources from sensu-go
  CHANGELOG.md
  testing/config/resources.json
  testing/config/staging-agent-0.yml.example
  testing/config/staging-agent-1.yml.example
  testing/config/staging-agent-2.yml.example
  testing/config/staging-backend.yml.example
Labels: ready-for-review

#2069 [Web UI] Remove keepalive timeout
  CHANGELOG.md
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
Labels: ready-for-review, web-ui

#2026 [Web UI] Introduce toast notification system
  dashboard/package.json
  dashboard/src/components/AnimatedLogo.js
  dashboard/src/components/AppLayout/AppLayout.js
  dashboard/src/components/AppRoot.js
  dashboard/src/components/createStyledComponent/createStyledComponent.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsExecuteAction.js
  dashboard/src/components/partials/ChecksList/ChecksList.js
  dashboard/src/components/partials/CircularProgress.js
  dashboard/src/components/partials/CollapsingMenu/CollapsingMenu.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsReRunAction.js
  dashboard/src/components/partials/ListHeader/ListHeader.js
  dashboard/src/components/partials/NotFound.js
  dashboard/src/components/relocation/ExecuteCheckStatusToast.js
  dashboard/src/components/relocation/Relocation.js
  dashboard/src/components/relocation/Toast.js
  dashboard/src/components/relocation/ToastConnector.js
  dashboard/src/components/relocation/ToastContainer.js
  dashboard/src/components/relocation/ToastWell.js
  dashboard/src/components/util/Loader.js
  dashboard/src/components/util/Timer.js
  dashboard/src/components/util/UnmountObserver.js
  dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/EnvironmentView/SilencesContent.js
  dashboard/src/components/views/NotFoundView.js
  dashboard/src/icons/IconGap.js
  dashboard/src/utils/uniqueId.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1974 [Web UI] Use a consistent description of entities everywhere
  dashboard/src/components/partials/EntitiesList/EntitiesListItem.js
  dashboard/src/components/partials/EntityStatusDescriptor/EntityStatusDescriptor.js
  dashboard/src/components/partials/EntityStatusDescriptor/index.js
  dashboard/src/components/partials/RelatedEntitiesCard/RelatedEntitiesCard.js
Labels: ready-for-review, web-ui

#2070 etcd authentication
  .gitignore
  CHANGELOG.md
  backend/backend.go
  backend/backend_test.go
  backend/cmd/start.go
  backend/cmd/version.go
  backend/config.go
  backend/etcd/etcd.go
  docker-compose.yaml
  packaging/files/backend.yml.example
  packaging/files/windows/backend.yml.example
  testing/e2e/process_test.go
Labels: ready-for-review

#2075 Allow updateCheck mutation to update individual fields
  backend/apid/graphql/mutations.go
  backend/apid/graphql/mutations_test.go
  backend/apid/graphql/services.go
  backend/apid/graphql/services_test.go
Labels: ready-for-review, web-ui

#2082 Remove omitempty for check output attribute
  CHANGELOG.md
  types/check.pb.go
  types/check.proto
Labels: ready-for-review

#2086 Deprecate custom-attributes
  CHANGELOG.md
  agent/agent.go
  cmd/sensu-agent/start.go
  packaging/files/agent.yml.example
  packaging/files/windows/agent.yml.example
  types/dynamic/dynamic.go
Labels: ready-for-review

#2087 Add a debug log message for interval timer initial offset
  CHANGELOG.md
  backend/schedulerd/check_timer.go
Labels: ready-for-review

#2091 Revoke etcd leases on shutdown in monitor
  CHANGELOG.md
  backend/backend.go
  backend/monitor/monitor_test.go
  backend/monitor/supervisor.go
Labels: ready-for-review

#2095 Fix interactive selection of output format
  CHANGELOG.md
  cli/client/config/config.go
  cli/commands/configure/configure.go
  cli/commands/configure/configure_test.go
Labels: ready-for-review

#2076 Fix keepalive events filtering
  CHANGELOG.md
  backend/eventd/eventd.go
  backend/eventd/silenced.go
  backend/eventd/silenced_test.go
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
  backend/pipelined/filter_test.go
  types/event.go
  types/event_test.go
Labels: ready-for-review

#2114 Use bbolt instead of boltdb/bolt
  Gopkg.lock
  Gopkg.toml
  asset/boltdb_manager.go
  asset/boltdb_manager_test.go
  asset/integration_test.go
  vendor/github.com/boltdb/bolt/bolt_arm.go
  vendor/go.etcd.io/bbolt/.gitignore
  vendor/go.etcd.io/bbolt/LICENSE
  vendor/go.etcd.io/bbolt/Makefile
  vendor/go.etcd.io/bbolt/README.md
  vendor/go.etcd.io/bbolt/appveyor.yml
  vendor/go.etcd.io/bbolt/bolt_386.go
  vendor/go.etcd.io/bbolt/bolt_amd64.go
  vendor/go.etcd.io/bbolt/bolt_arm.go
  vendor/go.etcd.io/bbolt/bolt_arm64.go
  vendor/go.etcd.io/bbolt/bolt_linux.go
  vendor/go.etcd.io/bbolt/bolt_openbsd.go
  vendor/go.etcd.io/bbolt/bolt_ppc.go
  vendor/go.etcd.io/bbolt/bolt_ppc64.go
  vendor/go.etcd.io/bbolt/bolt_ppc64le.go
  vendor/go.etcd.io/bbolt/bolt_s390x.go
  vendor/go.etcd.io/bbolt/bolt_unix.go
  vendor/go.etcd.io/bbolt/bolt_unix_solaris.go
  vendor/go.etcd.io/bbolt/bolt_windows.go
  vendor/go.etcd.io/bbolt/boltsync_unix.go
  vendor/go.etcd.io/bbolt/bucket.go
  vendor/go.etcd.io/bbolt/cursor.go
  vendor/go.etcd.io/bbolt/db.go
  vendor/go.etcd.io/bbolt/doc.go
  vendor/go.etcd.io/bbolt/errors.go
  vendor/go.etcd.io/bbolt/freelist.go
  vendor/go.etcd.io/bbolt/node.go
  vendor/go.etcd.io/bbolt/page.go
  vendor/go.etcd.io/bbolt/tx.go
Labels: ready-for-review

#2117 Fix sensuctl check update interactive values
  CHANGELOG.md
  cli/commands/check/interactive.go
Labels: ready-for-review

#2124 [Web UI] Fix bug in ExecuteCheckStatusToast component
  dashboard/src/components/relocation/ExecuteCheckStatusToast.js
Labels: ready-for-review, web-ui

#2127 Use EtcdClientTLSInfo for external etcd cluster
  CHANGELOG.md
  backend/backend.go
Labels: ready-for-review

#2129 Issue 2011-Validate Go code style formatting
  .circleci/config.yml
  asset/boltdb_manager.go
  asset/boltdb_manager_test.go
  asset/integration_test.go
  backend/apid/graphql/relay/node.go
  backend/apid/middlewares/allowlist.go
  backend/apid/middlewares/refresh_token.go
  backend/etcd/logrus_formatter.go
  backend/store/etcd/logrus_formatter.go
  build/ci/gofmt-linting-check.sh
  cli/elements/report/report.go
  scripts/gengraphql/gengraphql.go
Labels: ready-for-review

#2130 Use gofmt 1.10 for linting
  backend/backend.go
Labels: ready-for-review

#2098 Be case-insensitive when dealing with env. vars
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  agent/agent_test.go
  agent/assetmanager/manager.go
  agent/assetmanager/manager_test.go
  backend/apid/graphql/query_test.go
  backend/authorization/policy_test.go
  vendor/github.com/stretchr/objx/.codeclimate.yml
  vendor/github.com/stretchr/objx/.gitignore
  vendor/github.com/stretchr/objx/.travis.yml
  vendor/github.com/stretchr/objx/Gopkg.lock
  vendor/github.com/stretchr/objx/Gopkg.toml
  vendor/github.com/stretchr/objx/LICENSE
  vendor/github.com/stretchr/objx/README.md
  vendor/github.com/stretchr/objx/Taskfile.yml
  vendor/github.com/stretchr/objx/accessors.go
  vendor/github.com/stretchr/objx/conversions.go
  vendor/github.com/stretchr/objx/doc.go
  vendor/github.com/stretchr/objx/map.go
  vendor/github.com/stretchr/objx/mutations.go
  vendor/github.com/stretchr/objx/security.go
  vendor/github.com/stretchr/objx/type_specific_codegen.go
  vendor/github.com/stretchr/objx/value.go
  vendor/github.com/stretchr/testify/LICENCE.txt
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
Labels: ready-for-review

#2131 Increase duration delta in TestPeriodicKeepalive integration test
  CHANGELOG.md
  agent/agent_test.go
Labels: ready-for-review

#2102 Add test for privilege escalation in rbac
  CHANGELOG.md
  backend/authorization/authorization_test.go
Labels: ready-for-review

#2126 [Web UI] Checks Page Publishing/Unpublishing
  CHANGELOG.md
  backend/apid/graphql/schema/mutations.gql.go
  backend/apid/graphql/schema/mutations.graphql
  dashboard/src/components/partials/ChecksList/CheckSchedule.js
  dashboard/src/components/partials/ChecksList/ChecksList.js
  dashboard/src/components/partials/ChecksList/ChecksListHeader.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/relocation/PublishCheckStatusToast.js
  dashboard/src/icons/Unpublish.js
  dashboard/src/mutations/setCheckPublish.js
Labels: ready-for-review, web-ui
