Repository sensu/sensu-go, pull requests merged in 2018-11, with the labels that each got.

#2266 Add Groups for User, remove old roles
  backend/apid/actions/roles.go
  backend/apid/actions/users.go
  backend/apid/actions/users_test.go
  backend/apid/graphql/globalid/roles.go
  backend/apid/graphql/schema/user.gql.go
  backend/apid/graphql/schema/user.graphql
  backend/apid/routers/roles.go
  backend/apid/routers/users.go
  backend/seeds/seeds.go
  cli/client/interface.go
  cli/client/role.go
  cli/client/testing/mock_role_client.go
  cli/client/testing/mock_user_client.go
  cli/client/user.go
  cli/commands/commands.go
  cli/commands/role/LICENSE
  cli/commands/role/add_rule.go
  cli/commands/role/add_rule_test.go
  cli/commands/role/create.go
  cli/commands/role/create_test.go
  cli/commands/role/delete.go
  cli/commands/role/delete_test.go
  cli/commands/role/help.go
  cli/commands/role/info.go
  cli/commands/role/info_test.go
  cli/commands/role/list.go
  cli/commands/role/list_test.go
  cli/commands/role/remove_rule.go
  cli/commands/role/remove_rule_test.go
  cli/commands/user/add_group.go
  cli/commands/user/add_group_test.go
  cli/commands/user/create.go
  cli/commands/user/create_test.go
  cli/commands/user/help.go
  cli/commands/user/list.go
  cli/commands/user/list_test.go
  cli/commands/user/remove_group.go
  cli/commands/user/remove_group_test.go
  cli/commands/user/remove_groups.go
  cli/commands/user/remove_groups_test.go
  cli/commands/user/set_groups.go
  cli/commands/user/set_groups_test.go
  types/user.pb.go
  types/user.proto
Labels: ready-for-review, review

#2239 [Web UI] Include assets among check details
  CHANGELOG.md
  backend/apid/graphql/check.go
  backend/apid/graphql/check_test.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/services.go
  backend/apid/graphql/services_test.go
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js
Labels: ready-for-review, web-ui

#2240 [Web UI] Appropriate fallback when lastSeen value is missing
  CHANGELOG.md
  dashboard/src/components/partials/EntityStatusDescriptor/EntityStatusDescriptor.js
Labels: ready-for-review, web-ui

#2241 [Web UI] Remove lastSeen field from check result card
  CHANGELOG.md
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
Labels: ready-for-review, web-ui

#2282 Add new RBAC stores
  backend/apid/actions/error.go
  backend/apid/actions/roles.go
  backend/apid/apid.go
  backend/apid/graphql/error.go
  backend/apid/graphql/node.go
  backend/apid/graphql/schema/errors.gql.go
  backend/apid/middlewares/namespace.go
  backend/apid/routers/roles.go
  backend/apid/routers/routers.go
  backend/store/etcd/clusterrole_store.go
  backend/store/etcd/clusterrolebinding_store.go
  backend/store/etcd/role_store.go
  backend/store/etcd/rolebinding_store.go
  backend/store/etcd/store.go
  backend/store/etcd/store_test.go
  backend/store/key_builder.go
  backend/store/namespace.go
  backend/store/store.go
  cli/commands/role/create.go
  cli/commands/role/create_test.go
  testing/mockstore/clusterrole.go
  testing/mockstore/clusterrolebinding.go
  testing/mockstore/role.go
  testing/mockstore/rolebinding.go
  types/rbac.go
Labels: ready-for-review, review

#2285 Make the agent reusable in multiple main()s
  CHANGELOG.md
  agent/agent.go
  agent/cmd/root.go
  agent/cmd/start.go
  agent/config.go
  cmd/sensu-agent/logger.go
  cmd/sensu-agent/main.go
Labels: ready-for-review, review

#2273 Remove unused asset metadata field
  CHANGELOG.md
  backend/store/etcd/asset_store_test.go
  cli/commands/asset/create.go
  cli/commands/asset/create_test.go
  cli/commands/asset/info.go
  cli/commands/asset/info_test.go
  types/asset.go
  types/asset.pb.go
  types/asset.proto
Labels: ready-for-review, review

#2292 Use StringSlice for subscriptions flag in sensu-agent
  CHANGELOG.md
  agent/cmd/start.go
Labels: ready-for-review, review

#2293 Improve debug logging for event filtering in pipelind
  CHANGELOG.md
  backend/pipelined/filter.go
  util/logging/logging.go
Labels: ready-for-review, review

#2299 Re-introduce the namespace middleware for now
  backend/apid/apid.go
  backend/apid/middlewares/namespace.go
Labels: ready-for-review, review

#2302 Remove unused constraints in Gopkg.toml
  Gopkg.toml
Labels: ready-for-review, review

#2306 Add support for namespaces into path variable
  backend/apid/middlewares/namespace.go
  backend/apid/middlewares/namespace_test.go
Labels: ready-for-review, review

#2303 Add RBAC authorizer
  backend/authorization/LICENSE
  backend/authorization/rbac/LICENSE
  backend/authorization/rbac/rbac.go
  backend/authorization/rbac/rbac_test.go
  backend/store/etcd/rolebinding_store.go
Labels: ready-for-review, review

#2331 [Web UI] Avoid infinite loop when code cannot be highlighted
  CHANGELOG.md
  dashboard/src/components/CodeHighlight/CodeHighlight.js
Labels: bug, ready-for-review, review, web-ui

#2333 Use the get user endpoint to validate credentials
  backend/apid/routers/authentication.go
  cli/client/interface.go
  cli/client/testing/mock_user_client.go
  cli/client/user.go
  cli/commands/configure/configure.go
Labels: ready-for-review, review

#2334 List subjects in binding info subcommands
  cli/commands/clusterrolebinding/info.go
  cli/commands/rolebinding/info.go
Labels: ready-for-review

#2329 [Web UI] Update dashboard for object metadata
  backend/apid/graphql/check.go
  backend/apid/graphql/entity.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  backend/apid/graphql/schema/namespace.gql.go
  backend/apid/graphql/schema/silenced.gql.go
  backend/apid/graphql/schema/silenced.graphql
  backend/apid/graphql/silenced.go
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js
  dashboard/src/components/partials/ChecksList/ChecksList.js
  dashboard/src/components/partials/ClearSilencedEntriesDialog/Dialog.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
  dashboard/src/components/partials/EntityStatusDescriptor/EntityStatusDescriptor.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
  dashboard/src/components/partials/SilencesList/SilencesListItem.js
  dashboard/src/mutations/createSilence.js
  graphql/resolvers.go
Labels: ready-for-review, review, web-ui

#2305 [Web UI] MenuToolbar collapsing bug
  CHANGELOG.md
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsToolbar.js
  dashboard/src/components/partials/ToolbarMenu/Menu.js
  dashboard/src/components/relocation/ExecuteCheckStatusToast.js
  dashboard/src/components/relocation/Toast.js
Labels: ready-for-review, review, web-ui

#2339 [Web UI] Update filtering to use JS expressions
  dashboard/src/components/partials/ChecksList/ChecksListHeader.js
  dashboard/src/components/partials/EntitiesList/EntitiesListHeader.js
  dashboard/src/components/partials/EventsList/EventsListHeader.js
  dashboard/src/components/partials/EventsList/StatusMenu.js
  dashboard/src/components/relocation/ExecuteCheckStatusToast.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
Labels: ready-for-review, review, web-ui

#2341 ensure default resolver can traverse embedded structs
  backend/apid/graphql/globalid/entity.go
  backend/apid/graphql/globalid/handlers.go
  backend/apid/graphql/globalid/silences.go
  graphql/resolvers.go
  graphql/resolvers_test.go
Labels: ready-for-review, regression, review

#2347 Update changelog with release candidate
  CHANGELOG.md
Labels: ready-for-review, review

#2360 Fix resource leaks in the monitor and ring.
  CHANGELOG.md
  backend/cmd/start.go
  backend/messaging/message_bus.go
  backend/messaging/wizard_bus.go
  backend/messaging/wizard_bus_test.go
  backend/messaging/wizard_topic.go
  backend/monitor/monitor_test.go
  backend/monitor/supervisor.go
  backend/ring/ring.go
  backend/schedulerd/round_robin_scheduler.go
  backend/schedulerd/round_robin_scheduler_test.go
  docker-compose.yaml
  testing/mockbus/mock.go
  util/strings/strings.go
  util/strings/strings_test.go
Labels: ready-for-review, review

#2353 [Web UI] fixup creation of silences for entities
  CHANGELOG.md
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsSilenceAction.js
Labels: bug, ready-for-review, web-ui

#2364 Don't re-use otto VMs
  agent/agent_test.go
  agent/cmd/start.go
  backend/apid/graphql/namespace.go
  backend/pipelined/filter.go
  js/js.go
  js/vm_cache.go
  types/dynamic/redact.go
  types/dynamic/redact_test.go
  types/entity.go
Labels: ready-for-review, review

#2370 [Web UI] Event Details keepalive improvements
  CHANGELOG.md
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsToolbar.js
Labels: ready-for-review, review, web-ui

#2366 Merge the assets and {check,handler,mutator} environments
  CHANGELOG.md
  agent/check_handler.go
  backend/pipelined/handle.go
  backend/pipelined/mutate.go
  util/environment/LICENSE
  util/environment/environment.go
  util/environment/environment_test.go
Labels: ready-for-review, review

#2365 [Web UI] Fixup filtering by status on events list
  CHANGELOG.md
  dashboard/src/components/partials/EventsList/StatusMenu.js
Labels: ready-for-review, review, web-ui

#2369 Update README
  README.md
Labels: ready-for-review, review

#2375 Improve SSL/TLS clusters support
  CHANGELOG.md
  backend/apid/actions/health.go
  backend/apid/actions/health_test.go
  backend/apid/apid.go
  backend/backend.go
  backend/backend_test.go
  backend/cmd/start.go
  backend/config.go
  backend/etcd/etcd.go
  backend/etcd/testing.go
  backend/store/etcd/health_store.go
  backend/store/etcd/health_store_test.go
  backend/store/etcd/store_test.go
  backend/store/etcd/testutil/store.go
  backend/store/store.go
  packaging/files/backend.yml.example
  packaging/files/windows/backend.yml.example
  testing/e2e/process_test.go
  testing/mockstore/health.go
Labels: ready-for-review, review

#2378 Fix object listing in namespaces
  CHANGELOG.md
  backend/store/etcd/check_store.go
  backend/store/key_builder.go
  backend/store/key_builder_test.go
Labels: ready-for-review, review

#2380 [Web UI] Remove global `react/no-danger` suppression
  dashboard/.eslintrc.yml
  dashboard/src/components/CodeHighlight/CodeHighlight.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
Labels: ready-for-review, review, web-ui

#2379 [Web UI] Improve `NetworkError: undefined` message
  dashboard/.babelrc
  dashboard/.flowconfig
  dashboard/flow-typed/npm/es6-error_v4.x.x.js
  dashboard/package.json
  dashboard/src/errors/FetchError.js
  dashboard/src/utils/fetch.js
  dashboard/yarn.lock
Labels: ready-for-review, review, web-ui

#2383 Improve token substitution unit tests
  agent/token_test.go
Labels: ready-for-review, review

#2385 Remove filter-when support temporarily
  CHANGELOG.md
  cli/commands/create/create.go
  cli/commands/filter/help.go
Labels: ready-for-review, review

#2388 Fix a deadlock in the agent
  CHANGELOG.md
  agent/agent.go
  agent/agent_test.go
  util/retry/retry.go
Labels: ready-for-review, review

#2374 Update GraphQL Service for redesigned RBAC
  backend/apid/actions/error.go
  backend/apid/apid.go
  backend/apid/graphql/check.go
  backend/apid/graphql/check_test.go
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_test.go
  backend/apid/graphql/error.go
  backend/apid/graphql/fetch.go
  backend/apid/graphql/handler.go
  backend/apid/graphql/handler_test.go
  backend/apid/graphql/mockclient/errors.go
  backend/apid/graphql/mockclient/restclient.go
  backend/apid/graphql/mutations.go
  backend/apid/graphql/mutations_test.go
  backend/apid/graphql/namespace.go
  backend/apid/graphql/namespace_test.go
  backend/apid/graphql/node.go
  backend/apid/graphql/node_test.go
  backend/apid/graphql/query.go
  backend/apid/graphql/query_test.go
  backend/apid/graphql/restclient/client.go
  backend/apid/graphql/results.go
  backend/apid/graphql/service.go
  backend/apid/graphql/service_test.go
  backend/apid/graphql/services.go
  backend/apid/graphql/services_test.go
  backend/apid/graphql/silenced.go
  backend/apid/graphql/silenced_test.go
  backend/apid/graphql/viewer.go
  backend/apid/graphql/viewer_test.go
  backend/apid/middlewares/allowlist.go
  backend/apid/middlewares/allowlist_test.go
  backend/apid/middlewares/authentication.go
  backend/apid/middlewares/authentication_test.go
  backend/apid/middlewares/authorization.go
  backend/apid/middlewares/error.go
  backend/apid/routers/graphql.go
  backend/apid/routers/graphql_test.go
  backend/authentication/jwt/jwt.go
  backend/backend.go
  backend/dashboardd/dashboardd.go
  cli/client/asset.go
  cli/client/client.go
  cli/client/config/inmemory/inmemory.go
  cli/client/entity.go
  cli/client/error.go
  cli/client/event.go
  cli/client/filter.go
  cli/client/handler.go
  cli/client/interface.go
  cli/client/mutator.go
  cli/client/namespace.go
  cli/client/testing/mock_event_client.go
  types/context.go
Labels: ready-for-review, review

#2391 Remove a flaky test
  agent/agent_test.go
Labels: ready-for-review, review

#2394 Removes hooks and silenced from the Event type
  CHANGELOG.md
  types/event.go
  types/event.pb.go
  types/event.proto
  types/event_test.go
  util/logging/logging.go
Labels: ready-for-review, review

#2409 Fix a nil panic when logging non-check events
  CHANGELOG.md
  util/logging/logging.go
Labels: ready-for-review

#2415 Clean up and standardize routers/controllers
  backend/apid/actions/assets.go
  backend/apid/actions/assets_test.go
  backend/apid/actions/checks.go
  backend/apid/actions/checks_test.go
  backend/apid/actions/clusterrolebindings.go
  backend/apid/actions/clusterrolebindings_test.go
  backend/apid/actions/clusterroles.go
  backend/apid/actions/clusterroles_test.go
  backend/apid/actions/entities.go
  backend/apid/actions/entities_test.go
  backend/apid/actions/events.go
  backend/apid/actions/extensions.go
  backend/apid/actions/filters.go
  backend/apid/actions/filters_test.go
  backend/apid/actions/handlers.go
  backend/apid/actions/handlers_test.go
  backend/apid/actions/hooks.go
  backend/apid/actions/hooks_test.go
  backend/apid/actions/mutators.go
  backend/apid/actions/mutators_test.go
  backend/apid/actions/namespaces.go
  backend/apid/actions/namespaces_test.go
  backend/apid/actions/rolebindings.go
  backend/apid/actions/rolebindings_test.go
  backend/apid/actions/roles.go
  backend/apid/actions/roles_test.go
  backend/apid/actions/silenced.go
  backend/apid/actions/silenced_test.go
  backend/apid/actions/users.go
  backend/apid/routers/checks.go
  backend/apid/routers/checks_test.go
  backend/apid/routers/namespaces.go
  backend/apid/routers/namespaces_test.go
Labels: ready-for-review, review

#2414 [Web UI] SilencesList silence confirmation error removal
  dashboard/src/components/partials/SilencesList/SilencesList.js
  dashboard/src/components/partials/SilencesList/SilencesListHeader.js
  dashboard/src/components/partials/SilencesList/SilencesListItem.js
Labels: ready-for-review, review, web-ui

#2386 Simplify and expand README.md
  CONTRIBUTING.md
  README.md
Labels: documentation, ready-for-review

#2416 [Web UI] Remove re-run keepalives on Events and Checks List
  CHANGELOG.md
  dashboard/src/components/partials/ChecksList/ChecksListHeader.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/EventsList/EventsListHeader.js
  dashboard/src/components/partials/EventsList/EventsListItem.js
Labels: ready-for-review, review

#2080 [Web UI] Only display list item toolbar on hover
  dashboard/package.json
  dashboard/src/components/controller/HoverController.js
  dashboard/src/components/controller/ListController.js
  dashboard/src/components/partials/ChecksList/ChecksList.js
  dashboard/src/components/partials/ChecksList/ChecksListHeader.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/EntitiesList/EntitiesList.js
  dashboard/src/components/partials/EntitiesList/EntitiesListHeader.js
  dashboard/src/components/partials/EntitiesList/EntitiesListItem.js
  dashboard/src/components/partials/EventsList/EventsList.js
  dashboard/src/components/partials/EventsList/EventsListHeader.js
  dashboard/src/components/partials/EventsList/EventsListItem.js
  dashboard/src/components/partials/EventsList/EventsListToolbar.js
  dashboard/src/components/partials/ListHeader/ListHeader.js
  dashboard/src/components/partials/SilencesList/SilencesList.js
  dashboard/src/components/partials/SilencesList/SilencesListHeader.js
  dashboard/src/components/partials/SilencesList/SilencesListItem.js
  dashboard/src/components/partials/TableOverflowCell/TableOverflowCell.js
  dashboard/src/components/partials/TableSelectableRow/TableSelectableRow.js
  dashboard/src/components/partials/TableToolbarCell/FloatingTableToolbarCell.js
  dashboard/src/components/partials/TableToolbarCell/TableToolbarCell.js
  dashboard/src/components/partials/TableToolbarCell/index.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/EnvironmentView/SilencesContent.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#2427 Add ObjectMeta to AdhocRequest
  api/core/v2/adhoc.go
  api/core/v2/adhoc.pb.go
  api/core/v2/adhoc.proto
  backend/apid/graphql/mutations.go
Labels: ready-for-review

#2429 Grepory/monitor panic#2406
  CHANGELOG.md
  backend/monitor/supervisor.go
Labels: ready-for-review

#2428 Add list namespaces rule to system:user cluster role
  backend/seeds/seeds.go
Labels: ready-for-review

#2433 Namespace keepalive and check ttl monitors
  CHANGELOG.md
  backend/monitor/supervisor.go
Labels: ready-for-review

#2435 Fix user group management
  backend/apid/routers/users.go
Labels: bug, ready-for-review

#2430 [Web UI] Simplify Query Component
  dashboard/.eslintignore
  dashboard/.flowconfig
  dashboard/.prettierignore
  dashboard/flow-typed/npm/react-apollo_v2.x.x.js
  dashboard/package.json
  dashboard/src/components/util/Query.js
  dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/EnvironmentView/SilencesContent.js
  dashboard/src/errors/QueryAbortedError.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#2392 GraphQL service unauthorized err
  backend/apid/apid.go
  backend/apid/graphql/fetch.go
  backend/apid/graphql/namespace.go
  cli/client/asset.go
  cli/client/entity.go
  cli/client/filter.go
  cli/client/handler.go
Labels: ready-for-review, review

#2439 List across namespaces
  api/core/v2/context.go
  api/core/v2/namespace.go
  backend/apid/apid.go
  backend/apid/middlewares/namespace.go
  backend/apid/middlewares/namespace_test.go
  backend/apid/routers/assets.go
  backend/apid/routers/checks.go
  backend/apid/routers/checks_test.go
  backend/apid/routers/clusterrolebindings.go
  backend/apid/routers/clusterroles.go
  backend/apid/routers/entities.go
  backend/apid/routers/events.go
  backend/apid/routers/extensions.go
  backend/apid/routers/filters.go
  backend/apid/routers/handlers.go
  backend/apid/routers/hooks.go
  backend/apid/routers/mutators.go
  backend/apid/routers/namespaces.go
  backend/apid/routers/namespaces_test.go
  backend/apid/routers/rolebindings.go
  backend/apid/routers/roles.go
  backend/apid/routers/routers.go
  backend/apid/routers/silenced.go
  backend/apid/routers/users.go
  backend/store/etcd/asset_store.go
  backend/store/etcd/check_store.go
  backend/store/etcd/entity_store.go
  backend/store/etcd/event_store.go
  backend/store/etcd/extension_registry.go
  backend/store/etcd/filter_store.go
  backend/store/etcd/handler_store.go
  backend/store/etcd/helpers.go
  backend/store/etcd/helpers_test.go
  backend/store/etcd/hook_store.go
  backend/store/etcd/mutator_store.go
  backend/store/etcd/silenced_store.go
  backend/store/etcd/store.go
  backend/store/etcd/store_test.go
  backend/store/key_builder.go
  cli/client/error.go
  cli/commands/asset/list_test.go
  cli/commands/check/list_test.go
  cli/commands/entity/list_test.go
  cli/commands/event/list_test.go
  cli/commands/filter/list_test.go
  cli/commands/handler/list_test.go
  cli/commands/hook/list_test.go
  cli/commands/mutator/list_test.go
Labels: ready-for-review

#2443 Fix a bug where keepalives were not firing
  backend/monitor/supervisor.go
Labels: ready-for-review

#2445 Temporarily disable round-robin scheduling
  CHANGELOG.md
  backend/schedulerd/round_robin_scheduler.go
  backend/schedulerd/round_robin_scheduler_test.go
Labels: ready-for-review

#2436 Ensure password is not overwritten when users are updated
  CHANGELOG.md
  backend/apid/actions/users.go
  backend/authentication/bcrypt/bcrypt.go
  backend/authentication/bcrypt/bcrypt_test.go
  backend/seeds/seeds.go
  backend/store/etcd/user_store.go
  backend/store/etcd/user_store_test.go
Labels: ready-for-review

#2448 Grepory/disable extensions
  CHANGELOG.md
  cli/commands/commands.go
Labels: ready-for-review

#2437 [Web UI] Network error improvements - offline and retry fields
  dashboard/flow-typed/npm/react-apollo_v2.x.x.js
  dashboard/src/apollo/client.js
  dashboard/src/apollo/httpLink.js
  dashboard/src/apollo/resolvers/localNetwork.js
  dashboard/src/apollo/schema/client.graphql
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/apollo/stateLink.js
Labels: ready-for-review, web-ui

#2456 [Web UI] Set up GlobalAlert component
  dashboard/src/components/AppRoot.js
  dashboard/src/components/util/GlobalAlert.js
Labels: ready-for-review, web-ui

#2455 [Web UI] Network error banner
  dashboard/src/components/relocation/Banner.js
  dashboard/src/components/relocation/RetryConnectionBanner.js
  dashboard/src/mutations/retryLocalNetwork.js
Labels: ready-for-review, web-ui

#2460 Update changelog for 5.0.0
  CHANGELOG.md
Labels: ready-for-review

#2463 API URL
  .circleci/config.yml
  CHANGELOG.md
  backend/apid/apid.go
  backend/backend.go
  backend/backend_test.go
  backend/cmd/start.go
  backend/config.go
  backend/dashboardd/dashboardd.go
  build.ps1
  build.sh
  packaging/files/backend.yml.example
  packaging/files/windows/backend.yml.example
  testing/e2e/.gitignore
  testing/e2e/LICENSE
  testing/e2e/doc.go
  testing/e2e/main_test.go
  testing/e2e/process_test.go
Labels: ready-for-review

#2468 Fix API path used by entity create
  cli/client/entity.go
Labels: ready-for-review
