Repository sensu/sensu-go, pull requests merged in 2018-12, with the labels that each got.

#2474 Fix keepalive and check TTL bugs
  CHANGELOG.md
  backend/backend.go
  backend/eventd/eventd.go
  backend/eventd/integration_test.go
  backend/keepalived/integration_test.go
  backend/monitor/monitor_test.go
  backend/monitor/supervisor.go
  build.sh
  docker-compose.yaml
Labels: ready-for-review

#2475 [Web UI] Quick fix for FireFox resize event bug
  CHANGELOG.md
  dashboard/src/components/partials/ToolbarMenu/Menu.js
Labels: ready-for-review, web-ui

#2472 Return the response status if body is empty in sensuctl
  CHANGELOG.md
  cli/client/error.go
Labels: ready-for-review

#2487 Fix error in changelog
  CHANGELOG.md
Labels: ready-for-review

#2488 Remove e2e tests from appveyor test matrix
  .appveyor.yml
Labels: continuous integration, ready-for-review

#2486 Remove unused code coverage tool
  build.sh
  codecov.sh
  dashboard/package.json
  dashboard/yarn.lock
Labels: continuous integration, ready-for-review

#2451 [Web UI] Refetch query when api connection resumes
  dashboard/.flowconfig
  dashboard/src/components/util/Query.js
  dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/EnvironmentView/SilencesContent.js
Labels: ready-for-review, web-ui

#2482 [Web UI] Sort order updates
  CHANGELOG.md
  api/core/v2/event.go
  api/core/v2/event_test.go
  backend/apid/graphql/namespace.go
Labels: bug, ready-for-review, web-ui

#2440 [Web UI] Add tests for the RelativeDate component
  dashboard/package.json
  dashboard/src/components/RelativeDate/RelativeDate.test.js
  dashboard/src/setupTests.js
  dashboard/yarn.lock
Labels: ready-for-review, testing, web-ui

#2492 Docker/etcd advertise reachable addr
  CHANGELOG.md
  docker-compose.yaml
Labels: ready-for-review

#2501 Add the etcd client to the backend struct
  CHANGELOG.md
  backend/backend.go
Labels: ready-for-review

#2503 Add unsigned integer type to GraphQL schema
  CHANGELOG.md
  backend/apid/graphql/check.go
  backend/apid/graphql/json.go
  backend/apid/graphql/scalars.go
  backend/apid/graphql/scalars_test.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/json.graphql
  backend/apid/graphql/schema/scalars.gql.go
  backend/apid/graphql/schema/scalars.graphql
  backend/apid/graphql/service.go
Labels: ready-for-review

#2504 Do not build or test the backend for windows
  .appveyor.yml
  build.ps1
Labels: ready-for-review

#2516 Change the entity's status field to use uint type
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_test.go
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
Labels: ready-for-review

#2519 Fix issues around command execution in the agent
  CHANGELOG.md
  agent/check_handler.go
  command/command.go
  command/proc_windows.go
  util/environment/environment.go
  util/environment/environment_posix.go
  util/environment/environment_posix_test.go
  util/environment/environment_test.go
  util/environment/environment_windows.go
  util/environment/environment_windows_test.go
Labels: ready-for-review

#2524 Add backend environment to handler & mutator execution requests
  CHANGELOG.md
  backend/pipelined/handle.go
  backend/pipelined/mutate.go
Labels: ready-for-review

#2512 Return empty slice instead of nil for assets
  CHANGELOG.md
  backend/store/etcd/asset_store.go
Labels: ready-for-review

#2515 Allow hook creation with sensuctl create -f
  CHANGELOG.md
  api/core/v2/hook.go
Labels: ready-for-review

#2485 [Web UI] Fix firefox rendering bug
  CHANGELOG.md
  dashboard/src/icons/Error.js
  dashboard/src/icons/OK.js
  dashboard/src/icons/Unknown.js
  dashboard/src/icons/Warn.js
Labels: ready-for-review, web-ui

#2502 Fix a bug where keepalive events only fire once
  CHANGELOG.md
  backend/monitor/monitor_test.go
  backend/monitor/supervisor.go
Labels: ready-for-review

#2547 TLS improvements for sensu-agent
  CHANGELOG.md
  agent/cmd/start.go
  api/core/v2/tls.go
  backend/cmd/start.go
Labels: ready-for-review

#2549 Use interval, not ttl, for keepalive event refresh
  backend/monitor/monitor_test.go
  backend/monitor/supervisor.go
Labels: ready-for-review

#2556 Update CHANGELOG for v5.1.0
  CHANGELOG.md
Labels: ready-for-review

#2564 Updated contributing details for Enterprise packaging clarity/transparency
  CONTRIBUTING.md
  README.md
Labels: ready-for-review

#2539 Add test cases for entity system information
  api/core/v2/entity.go
  asset/filtered_manager_test.go
Labels: ready-for-review

#2537 Update backend config example
  packaging/files/backend.yml.example
Labels: ready-for-review
