Repository sensu/sensu-go, pull requests merged in 2018-05, with the labels that each got.

#1406 [GraphQL] Use string to represent ID scalar
  backend/apid/graphql/asset.go
  backend/apid/graphql/check.go
  backend/apid/graphql/entity.go
  backend/apid/graphql/environment.go
  backend/apid/graphql/event.go
  backend/apid/graphql/handler.go
  backend/apid/graphql/hook.go
  backend/apid/graphql/mutations.go
  backend/apid/graphql/organization.go
  backend/apid/graphql/query.go
  backend/apid/graphql/rbac.go
  backend/apid/graphql/schema/asset.gql.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/environment.gql.go
  backend/apid/graphql/schema/event.gql.go
  backend/apid/graphql/schema/handler.gql.go
  backend/apid/graphql/schema/hook.gql.go
  backend/apid/graphql/schema/mutations.gql.go
  backend/apid/graphql/schema/mutator.gql.go
  backend/apid/graphql/schema/organization.gql.go
  backend/apid/graphql/schema/rbac.gql.go
  backend/apid/graphql/schema/schema.gql.go
  backend/apid/graphql/user.go
  graphql/generator/object.go
  graphql/generator/types.go
Labels: ready-for-review, web-ui

#1405 [GraphQL] Add mutation for deleting events
  backend/apid/graphql/entity.go
  backend/apid/graphql/environment.go
  backend/apid/graphql/globalid/events.go
  backend/apid/graphql/globalid/events_test.go
  backend/apid/graphql/mutations.go
  backend/apid/graphql/mutations_test.go
  backend/apid/graphql/query.go
  backend/apid/graphql/schema/mutations.gql.go
  backend/apid/graphql/schema/mutations.graphql
  backend/apid/graphql/services.go
Labels: ready-for-review, web-ui

#1424 Fix bug in topic done chan closed on subscribe
  CHANGELOG.md
  backend/agentd/session.go
  backend/messaging/wizard_bus.go
  backend/messaging/wizard_bus_test.go
  backend/messaging/wizard_topic.go
Labels: ready-for-review

#1413 Update build.ps1 to use version tool
  .appveyor.yml
  build.ps1
Labels: ready-for-review

#1396 Add validation for flap thresholds.
  types/check.go
  types/check_test.go
Labels: ready-for-review

#1435 Ensure event entity has a last_seen time.
  CHANGELOG.md
  agent/entity.go
Labels: ready-for-review

#1419 Add CLI support for metric_format and metric_handlers
  CHANGELOG.md
  cli/commands/check/create.go
  cli/commands/check/help.go
  cli/commands/check/info.go
  cli/commands/check/interactive.go
  cli/commands/check/list.go
  cli/commands/check/subcommands/remove_metric_format.go
  cli/commands/check/subcommands/remove_metric_format_test.go
  cli/commands/check/subcommands/remove_metric_handlers.go
  cli/commands/check/subcommands/remove_metric_handlers_test.go
  cli/commands/check/subcommands/set_metric_format.go
  cli/commands/check/subcommands/set_metric_format_test.go
  cli/commands/check/subcommands/set_metric_handlers.go
  cli/commands/check/subcommands/set_metric_handlers_test.go
  types/check.go
Labels: ready-for-review

#1436 statsd listens on TCP for Windows
  CHANGELOG.md
  agent/agent.go
Labels: ready-for-review

#1410 [GraphQL] Use offset-based pagination for large connections
  backend/apid/graphql/environment.go
  backend/apid/graphql/pagination.go
  backend/apid/graphql/relay.go
  backend/apid/graphql/relay/array_connections.go
  backend/apid/graphql/relay/connections.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  backend/apid/graphql/schema/environment.gql.go
  backend/apid/graphql/schema/environment.graphql
  backend/apid/graphql/schema/event.gql.go
  backend/apid/graphql/schema/event.graphql
  backend/apid/graphql/schema/pagination.gql.go
  backend/apid/graphql/schema/pagination.graphql
  backend/apid/graphql/schema/relay.gql.go
  backend/apid/graphql/schema/relay.graphql
  backend/apid/graphql/schema/viewer.gql.go
  backend/apid/graphql/schema/viewer.graphql
  backend/apid/graphql/service.go
  backend/apid/graphql/util.go
  backend/apid/graphql/viewer.go
  dashboard/src/components/CheckList.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  types/check.go
  types/check_test.go
  types/entity.go
  types/entity_test.go
Labels: ready-for-review, web-ui

#1427 InfluxDB Transformer Implementation
  CHANGELOG.md
  agent/check_handler.go
  agent/transformers/influx_db.go
  agent/transformers/influx_db_test.go
  agent/transformers/transformer.go
  handlers/influx-db/main.go
Labels: ready-for-review

#1438 Use CombinedOutput to run yarn.
  dashboard/assets_generate.go
Labels: ready-for-review

#1425 Support for Nagios performance data metrics
  CHANGELOG.md
  agent/check_handler.go
  agent/check_handler_internal_test.go
  agent/transformers/nagios.go
  agent/transformers/nagios_test.go
Labels: ready-for-review

#1446 Add e2e test for metric extraction
  CHANGELOG.md
  testing/e2e/metric_extraction_test.go
Labels: ready-for-review

#1447 Improve display and ergonomics of silenced entries.
  CHANGELOG.md
  cli/commands/silenced/info.go
  cli/commands/silenced/interactive.go
  cli/commands/silenced/list.go
  cli/commands/timeutil/time.go
Labels: ready-for-review

#1421 [Web UI] Add delete & resolve actions to details page
  dashboard/src/apollo/resolvers/deleted.js
  dashboard/src/apollo/stateLink.js
  dashboard/src/components/ButtonSet/ButtonSet.js
  dashboard/src/components/ButtonSet/index.js
  dashboard/src/components/Content/Content.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/Loader.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsConfiguration.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsDeleteAction.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsRelatedEntities.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsResolveAction.js
  dashboard/src/components/partials/EventDetailsContainer/index.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/mutations/deleteEvent.js
  dashboard/src/mutations/resolveEvent.js
Labels: ready-for-review, web-ui

#1441 [GraphQL] Fixup issues with resolving entity fields
  backend/apid/graphql/entity.go
  backend/apid/graphql/json.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  backend/apid/graphql/schema/json.gql.go
  backend/apid/graphql/schema/json.graphql
  backend/apid/graphql/schema/pagination.gql.go
  backend/apid/graphql/service.go
Labels: ready-for-review, web-ui

#1398 [Web UI] Entities page
  dashboard/src/components/AppContent.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/StatusListItem.js
  dashboard/src/components/TableList/TableList.js
  dashboard/src/components/TableList/TableListHeader.js
  dashboard/src/components/partial/EntitiesList/EntitiesList.js
  dashboard/src/components/partial/EntitiesList/EntitiesListHeader.js
  dashboard/src/components/partial/EntitiesList/EntitiesListItem.js
  dashboard/src/components/partial/EntitiesList/index.js
  dashboard/src/components/partial/StatusMenu.js
  dashboard/src/components/util/NamespaceLink.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
Labels: ready-for-review, web-ui

#1456 [Web UI] Entity details page
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_test.go
  backend/apid/graphql/environment_test.go
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  backend/apid/graphql/services_test.go
  dashboard/src/components/InlineLink/InlineLink.js
  dashboard/src/components/InlineLink/index.js
  dashboard/src/components/Maybe/Maybe.js
  dashboard/src/components/Monospaced/Monospaced.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsContainer.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsEvents.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
  dashboard/src/components/partials/EntityDetailsContainer/index.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/RelatedEntitiesCard/RelatedEntitiesCard.js
  dashboard/src/components/partials/RelatedEntitiesCard/index.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
Labels: ready-for-review, web-ui

#1457 [Web UI] Remove placeholder dashboard
  dashboard/src/components/Drawer.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/Preferences.js
  dashboard/src/components/QuickNav.js
  dashboard/src/components/partial/EntitiesList/EntitiesList.js
  dashboard/src/components/views/EnvironmentView/DashboardContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/LoginView.js
  dashboard/src/themes/Bubblegum.js
  dashboard/src/themes/bubblegum.js
  dashboard/src/themes/index.js
Labels: ready-for-review

#1474 [Web UI] Fixup resolve event
  dashboard/src/components/EventsListItem.js
Labels: web-ui

#1454 Check output metric extraction field names should be more specific
  CHANGELOG.md
  agent/check_handler.go
  agent/check_handler_internal_test.go
  agent/transformer.go
  agent/transformers/graphite.go
  agent/transformers/influx_db.go
  backend/apid/actions/checks.go
  cli/commands/check/create.go
  cli/commands/check/help.go
  cli/commands/check/info.go
  cli/commands/check/interactive.go
  cli/commands/check/list.go
  cli/commands/check/subcommands/remove_metric_format.go
  cli/commands/check/subcommands/remove_metric_format_test.go
  cli/commands/check/subcommands/remove_metric_handlers.go
  cli/commands/check/subcommands/remove_metric_handlers_test.go
  cli/commands/check/subcommands/set_metric_format.go
  cli/commands/check/subcommands/set_metric_format_test.go
  cli/commands/check/subcommands/set_metric_handlers.go
  cli/commands/check/subcommands/set_metric_handlers_test.go
  testing/e2e/metric_extraction_test.go
  types/check.go
  types/check.pb.go
  types/check.proto
  types/check_test.go
Labels: ready-for-review

#1469 [Web UI] Rename 'Configuration' card to 'Summary'
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
Labels: ready-for-review, web-ui

#1475 Trim git describe output
  version/cmd/version/version.go
Labels: ready-for-review

#1458 Trim whitespace from check output in opentsdb transformer
  CHANGELOG.md
  agent/transformers/influx_db_test.go
  agent/transformers/nagios_test.go
  agent/transformers/opentsdb.go
  agent/transformers/opentsdb_test.go
Labels: ready-for-review

#1476 Add logging around event pipeline
  CHANGELOG.md
  backend/pipelined/handle.go
  util/logging/logging.go
Labels: ready-for-review

#1486 Audit event polymorphism
  CHANGELOG.md
  agent/entity.go
  agent/event.go
  agent/transformers/nagios.go
  backend/agentd/entity.go
  backend/apid/actions/events.go
  backend/apid/graphql/globalid/events.go
  backend/apid/graphql/mutations.go
  backend/eventd/eventd.go
  backend/eventd/flapping.go
  backend/eventd/silenced.go
  backend/keepalived/deregisterer.go
  backend/keepalived/keepalived.go
  backend/pipelined/mutate.go
  handlers/influx-db/main.go
  handlers/slack/main.go
  rpc/extension/example/main.go
  types/event.go
  util/logging/logging.go
Labels: ready-for-review

#1488 Fix handler validation.
  CHANGELOG.md
  types/handler.go
  types/handler_test.go
  types/validators.go
  types/validators_test.go
Labels: ready-for-review

#1485 Fix a bug where zero-valued metrics are not displayed.
  CHANGELOG.md
  types/metrics.pb.go
  types/metrics.proto
Labels: ready-for-review

#1492 Deprecated hooks, silenced fields in event proto
  CHANGELOG.md
  types/event.pb.go
  types/event.proto
Labels: ready-for-review

#1477 Prevent panic on method event.IsSilenced with metrics
  CHANGELOG.md
  types/event_test.go
Labels: ready-for-review

#1491 Add round-robin scheduling to sensuctl.
  CHANGELOG.md
  cli/commands/check/create.go
  cli/commands/check/help.go
  cli/commands/check/interactive.go
  cli/commands/check/subcommands/set_round_robin.go
  cli/commands/check/subcommands/set_round_robin_test.go
Labels: ready-for-review

#1499 Log statsd errors
  CHANGELOG.md
  agent/agent.go
  agent/statsd_server_test.go
Labels: ready-for-review

#1505 Add circleci configuration
  .circleci/config.yaml
Labels: ready-for-review

#1513 Fix default env description typo
  backend/store/etcd/organization_store.go
Labels: ready-for-review

#1445 [Web UI] Silencing entry dialog
  dashboard/config/packageHasESNext.js
  dashboard/package.json
  dashboard/src/components/AppFrame.js
  dashboard/src/components/CheckList.js
  dashboard/src/components/Code.js
  dashboard/src/components/DateFormatter/DateFormatter.js
  dashboard/src/components/Drawer.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/partials/EntitiesList/EntitiesList.js
  dashboard/src/components/partials/EntitiesList/EntitiesListHeader.js
  dashboard/src/components/partials/EntitiesList/EntitiesListItem.js
  dashboard/src/components/partials/EntitiesList/index.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/SilenceEntryDialog.js
  dashboard/src/components/partials/SilenceEntryForm/SilenceEntryForm.js
  dashboard/src/components/partials/SilenceEntryForm/SilenceEntryFormCheckPanel.js
  dashboard/src/components/partials/SilenceEntryForm/SilenceEntryFormExpirationPanel.js
  dashboard/src/components/partials/SilenceEntryForm/SilenceEntryFormPanel.js
  dashboard/src/components/partials/SilenceEntryForm/SilenceEntryFormReasonPanel.js
  dashboard/src/components/partials/SilenceEntryForm/SilenceEntryFormSchedulePanel.js
  dashboard/src/components/partials/SilenceEntryForm/SilenceEntryFormSubscriptionPanel.js
  dashboard/src/components/partials/SilenceEntryForm/SilenceEntryFormTargetsPanel.js
  dashboard/src/components/partials/SilenceEntryForm/index.js
  dashboard/src/components/partials/StatusMenu.js
  dashboard/src/components/util/Loader.js
  dashboard/src/components/util/RenderCounter.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/themes/defaults.js
  dashboard/src/utils/date.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1526 Fix a bug where URIPath for Environment was wrong.
  CHANGELOG.md
  types/environment.go
Labels: ready-for-review

#1495 Add create method for entities
  CHANGELOG.md
  backend/apid/actions/entities.go
  backend/apid/actions/entities_test.go
  backend/apid/routers/entities.go
Labels: ready-for-review

#1524 Fix a hook encoding bug related to embedding.
  CHANGELOG.md
  types/hook.pb.go
  types/hook.proto
  types/hook_test.go
Labels: ready-for-review

#1532 Install yarn during travis before_install step
  .travis.yml
  build.sh
Labels: ready-for-review

#1506 [GraphQL] Add Silenced type to schema
  backend/apid/actions/silenced.go
  backend/apid/actions/silenced_test.go
  backend/apid/graphql/check.go
  backend/apid/graphql/entity.go
  backend/apid/graphql/environment.go
  backend/apid/graphql/environment_test.go
  backend/apid/graphql/globalid/components.go
  backend/apid/graphql/globalid/components_test.go
  backend/apid/graphql/globalid/silences.go
  backend/apid/graphql/mutations.go
  backend/apid/graphql/mutations_test.go
  backend/apid/graphql/namespace.go
  backend/apid/graphql/query_test.go
  backend/apid/graphql/schema/environment.gql.go
  backend/apid/graphql/schema/environment.graphql
  backend/apid/graphql/schema/mutations.gql.go
  backend/apid/graphql/schema/mutations.graphql
  backend/apid/graphql/schema/namespace.gql.go
  backend/apid/graphql/schema/namespace.graphql
  backend/apid/graphql/schema/node.gql.go
  backend/apid/graphql/schema/node.graphql
  backend/apid/graphql/schema/silenced.gql.go
  backend/apid/graphql/schema/silenced.graphql
  backend/apid/graphql/service.go
  backend/apid/graphql/services.go
  backend/apid/graphql/services_test.go
  backend/apid/graphql/silenced.go
  backend/apid/graphql/util.go
  backend/apid/routers/silenced.go
  scripts/proto2graphql/proto2graphql.go
Labels: ready-for-review, web-ui

#1533 [Web UI] Fix prettier package script
  dashboard/package.json
Labels: ready-for-review, web-ui

#1455 Improve version handling for nightly and dev builds
  CHANGELOG.md
  Makefile
  version/cmd/version/version.go
  version/sort.go
  version/sort_test.go
  version/version.go
  version/version_test.go
Labels: ready-for-review

#1543 [Web UI] Trap uncaught errors and promise rejections
  dashboard/package.json
  dashboard/src/.eslintrc
  dashboard/src/apollo/authLink.js
  dashboard/src/apollo/client.js
  dashboard/src/apollo/errorLink.js
  dashboard/src/apollo/httpLink.js
  dashboard/src/apollo/localStorageSync.js
  dashboard/src/components/AppWrapper.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsDeleteAction.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsResolveAction.js
  dashboard/src/components/util/ErrorBoundary.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/LoginView.js
  dashboard/src/errors/FetchError.js
  dashboard/src/errors/ReactError.js
  dashboard/src/exceptionHandler.js
  dashboard/src/index.js
  dashboard/src/mutations/createTokens.js
  dashboard/src/mutations/deleteEvent.js
  dashboard/src/mutations/invalidateTokens.js
  dashboard/src/mutations/refreshTokens.js
  dashboard/src/mutations/resolveEvent.js
  dashboard/src/utils/authAPI.js
  dashboard/src/utils/fetch.js
  dashboard/src/utils/promise.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1539 [Web UI] Define client schema extensions
  build.sh
  dashboard/.eslintrc.yml
  dashboard/.gitignore
  dashboard/.graphqlconfig.yml
  dashboard/package.json
  dashboard/scripts/LICENSE
  dashboard/scripts/updateSchema.go
  dashboard/scripts/updateSchema.js
  dashboard/src/apollo/client.js
  dashboard/src/apollo/introspectionLink.js
  dashboard/src/apollo/schema/.gitattributes
  dashboard/src/apollo/schema/client.graphql
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/apollo/schema/combinedIntrospection.macro.js
  dashboard/src/apollo/schema/combinedTypes.macro.js
  dashboard/yarn.lock
Labels: ready-for-review

#1546 Entity/create cli
  .appveyor.yml
  .travis.yml
  CHANGELOG.md
  backend/apid/actions/entities.go
  backend/apid/actions/entities_test.go
  backend/apid/routers/entities.go
  cli/client/entity.go
  cli/client/interface.go
  cli/client/testing/mock_entity_client.go
  cli/commands/entity/create.go
  cli/commands/entity/create_test.go
  cli/commands/entity/help.go
  cli/commands/entity/interactive.go
  cli/commands/entity/update.go
Labels: ready-for-review

#1554 Pass CI env var to sensu-go-build docker image
  build.sh
Labels: ready-for-review

#1555 [Web UI] Prevent cascading errors when token refresh fails
  dashboard/package.json
  dashboard/src/apollo/authLink.js
  dashboard/src/apollo/resolvers/auth.js
  dashboard/src/errors/FetchError.js
  dashboard/src/utils/authAPI.js
  dashboard/src/utils/promise.js
  dashboard/src/utils/promise.test.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1558 Don't allow unknown fields when creating resources.
  CHANGELOG.md
  types/wrapper.go
  types/wrapper_test.go
Labels: ready-for-review

#1560 Wipe all artifacts when clean task is invoked
  Makefile
Labels: ready-for-review

#1561 Add the wrapped-json format to sensuctl
  CHANGELOG.md
  cli/cli.go
  cli/client/config/config.go
  cli/commands/asset/info.go
  cli/commands/asset/list.go
  cli/commands/check/info.go
  cli/commands/check/list.go
  cli/commands/configure/configure.go
  cli/commands/entity/info.go
  cli/commands/entity/list.go
  cli/commands/environment/list.go
  cli/commands/event/info.go
  cli/commands/event/list.go
  cli/commands/extension/list.go
  cli/commands/filter/info.go
  cli/commands/filter/list.go
  cli/commands/handler/info.go
  cli/commands/handler/list.go
  cli/commands/helpers/flags.go
  cli/commands/helpers/json.go
  cli/commands/helpers/json_test.go
  cli/commands/helpers/print.go
  cli/commands/hook/info.go
  cli/commands/hook/list.go
  cli/commands/mutator/info.go
  cli/commands/mutator/list.go
  cli/commands/organization/list.go
  cli/commands/role/list.go
  cli/commands/role/list_rules.go
  cli/commands/silenced/info.go
  cli/commands/silenced/list.go
  cli/commands/user/list.go
  testing/e2e/sensuctl_create_test.go
  types/check.go
  types/extension.go
  types/hook.go
  types/wrapper.go
Labels: ready-for-review

#1566 Fix an aliasing bug in ResolveResource.
  CHANGELOG.md
  types/typemap.go
  types/typemap.tmpl
  types/typemap_test.go
Labels: ready-for-review

#1552 Generate silenced id if empty; add log middleware to NotFoundHandler
  CHANGELOG.md
  backend/apid/apid.go
  types/silenced.go
Labels: ready-for-review

#1563 [Web UI] Update browser polyfills
  dashboard/.babelrc
  dashboard/.eslintrc.yml
  dashboard/config/polyfills.js
  dashboard/config/webpack.config.js
  dashboard/package.json
  dashboard/src/.eslintrc
  dashboard/src/apollo/resolvers/auth.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/RelativeDate/RelativeDate.js
  dashboard/src/index.js
  dashboard/src/modernizr.macro.js
  dashboard/src/polyfill.js
  dashboard/src/utils/authAPI.js
  dashboard/src/utils/fetch.js
  dashboard/src/utils/promise.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1562 Refactoring of sensu-backend entry point
  CHANGELOG.md
  backend/backend.go
  backend/backend_test.go
  backend/cmd/logger.go
  backend/cmd/main.go
  backend/cmd/root.go
  backend/cmd/start.go
  backend/config.go
  build.ps1
  build.sh
  cmd/sensu-backend/LICENSE
  cmd/sensu-backend/logger.go
  cmd/sensu-backend/main.go
Labels: ready-for-review

#1575 Remove Sensu.js cached file
  dashboard/src/themes/Sensu.js
Labels: ready-for-review

#1585 Make metric event logs more specific with additional fields
  CHANGELOG.md
  util/logging/logging.go
Labels: ready-for-review

#1605 [Web UI] Create error display modal
  dashboard/config/webpack.config.js
  dashboard/package.json
  dashboard/src/.eslintrc
  dashboard/src/buildInfo.macro.js
  dashboard/src/components/ErrorRoot.js
  dashboard/src/exceptionHandler.js
  dashboard/src/renderError.js
  dashboard/yarn.lock
Labels: web-ui

#1607 [GraphQL] Support request batching
  Gopkg.lock
  Gopkg.toml
  backend/apid/routers/graphql.go
  backend/apid/routers/graphql_test.go
  dashboard/package.json
  dashboard/src/apollo/httpLink.js
  dashboard/yarn.lock
  vendor/github.com/graphql-go/graphql/testutil/introspection_query.go
  vendor/github.com/graphql-go/graphql/testutil/rules_test_harness.go
  vendor/github.com/graphql-go/graphql/testutil/testutil.go
Labels: ready-for-review, web-ui

#1616 [Web UI] Fix bug in error modal
  dashboard/src/components/ErrorRoot.js
Labels: ready-for-review, web-ui

#1617 [Web UI] Standardize "sign in" and "sign out" copy
  dashboard/src/components/AppRoot.js
  dashboard/src/components/util/DefaultRedirect.js
  dashboard/src/components/views/SignInView.js
Labels: ready-for-review, web-ui

#1619 [Web UI] Create wrapped <Query> component
  dashboard/src/components/AppWrapper.js
  dashboard/src/components/util/Query.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/errors/QueryAbortedError.js
Labels: ready-for-review, web-ui

#1625 [Web UI] Add ESLint rule 'curly'
  dashboard/.eslintrc.yml
  dashboard/src/apollo/authLink.js
  dashboard/src/apollo/client.js
  dashboard/src/apollo/schema/combinedTypes.macro.js
  dashboard/src/components/RelativeDate/RelativeDate.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsDeleteAction.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsResolveAction.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/utils/checkStatus.js
  dashboard/src/utils/consecutivePairs.js
  dashboard/src/utils/dispatcher.js
Labels: ready-for-review, web-ui

#1606 [Web UI] Add filtering to the entities page
  .travis.yml
  dashboard/package.json
  dashboard/src/apollo/schema/client.graphql
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/components/ButtonIcon/ButtonIcon.js
  dashboard/src/components/ButtonIcon/index.js
  dashboard/src/components/CollapsingMenu/Button.js
  dashboard/src/components/CollapsingMenu/CollapsingMenu.js
  dashboard/src/components/CollapsingMenu/MenuItem.js
  dashboard/src/components/CollapsingMenu/index.js
  dashboard/src/components/Content/Content.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/QueryParams/QueryParam.js
  dashboard/src/components/QueryParams/QueryParams.js
  dashboard/src/components/QueryParams/index.js
  dashboard/src/components/QueryParams/withQueryParams.js
  dashboard/src/components/SearchBox.js
  dashboard/src/components/SearchBox/SearchBox.js
  dashboard/src/components/SearchBox/index.js
  dashboard/src/components/VerticalDisclosureButton/VerticalDisclosureButton.js
  dashboard/src/components/VerticalDisclosureButton/index.js
  dashboard/src/components/partials/EntitiesList/EntitiesList.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/ListToolbar.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/modernizr.macro.js
  dashboard/src/polyfill.js
Labels: ready-for-review, web-ui

#1614 Refactor/check scheduler
  .gitignore
  backend/schedulerd/check_scheduler.go
  backend/schedulerd/check_scheduler_test.go
  backend/schedulerd/check_scheduler_unit_test.go
  backend/schedulerd/check_timer.go
  backend/schedulerd/check_timer_test.go
  backend/schedulerd/check_watcher.go
  backend/schedulerd/check_watcher_test.go
  backend/schedulerd/executor.go
  backend/schedulerd/executor_test.go
  backend/schedulerd/proxy_check_test.go
  backend/schedulerd/schedule_manager.go
  backend/schedulerd/schedulerd.go
  backend/schedulerd/schedulerd_test.go
  backend/schedulerd/state_manager.go
  backend/schedulerd/synchronizer.go
  backend/schedulerd/synchronizer_test.go
  backend/store/etcd/extension_registry.go
  backend/store/etcd/helpers.go
  backend/store/etcd/watchers.go
  backend/store/key_parser.go
  backend/store/key_parser_test.go
  testing/e2e/check_subdue_test.go
  types/check.go
  types/check_test.go
  util/time/LICENSE
  util/time/time.go
  util/time/time_test.go
Labels: ready-for-review
