Repository sensu/sensu-go, pull requests merged in 2018-03, with the labels that each got.

#1092 [Web UI] Sort events based on their status and timestamp
  agent/backend_selector_test.go
  backend/apid/graphql/check.go
  backend/apid/graphql/environment.go
  backend/apid/graphql/query.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/environment.gql.go
  backend/apid/graphql/schema/environment.graphql
  backend/apid/graphql/schema/schema.gql.go
  backend/apid/graphql/schema/schema.graphql
  backend/apid/graphql/schema/viewer.gql.go
  backend/apid/graphql/schema/viewer.graphql
  backend/apid/graphql/service.go
  backend/apid/graphql/viewer.go
  dashboard/src/components/EventsContainer.js
  dashboard/src/pages/EventsPage.js
  dashboard/src/routes.js
  types/event.go
  types/event_test.go
Labels: ready-for-review, web-ui

#1098 Minor cleanup
  build.sh
Labels: ready-for-review

#1100 Use uint32 for status so it's not empty when marshalling
  CHANGELOG.md
  agent/check_handler.go
  agent/sockets_test.go
  backend/eventd/eventd_test.go
  backend/pipelined/filter_test.go
  testing/e2e/keepalive_test.go
  testing/e2e/round_robin_scheduling_test.go
  types/check.go
  types/check.pb.go
  types/check.proto
  types/check_test.go
  types/event.go
  types/event_test.go
  types/v1/check.go
Labels: ready-for-review

#1106 Fix integration tests that verify a check status
  backend/eventd/integration_test.go
  backend/keepalived/integration_test.go
Labels: ready-for-review

#1094 Refactor tests to not use testify.Suite.
  agent/assetmanager/asset_test.go
  agent/assetmanager/manager_test.go
  agent/assetmanager/set_test.go
  agent/assetmanager/store_test.go
  backend/keepalived/keepalived_test.go
  cli/commands/completion/cmd_test.go
  cli/elements/list/list_test.go
  testing/e2e/keepalive_test.go
Labels: ready-for-review

#1110 Update/cli guidelines
  CHANGELOG.md
  cli/GUIDELINES.md
Labels: ready-for-review

#1116 Change travis badge to travis-ci.org
  CHANGELOG.md
  README.md
Labels: ready-for-review

#1112 [Web] Bulk Actions - Resolving
  backend/apid/apid.go
  backend/apid/graphql/mutations.go
  backend/apid/graphql/schema/mutations.gql.go
  backend/apid/graphql/schema/mutations.graphql
  backend/apid/graphql/service.go
  backend/apid/routers/graphql.go
  dashboard/.eslintrc.yml
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsContainerMenu.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/mutations/ResolveEventMutation.js
  dashboard/src/utils/authentication/index.js
Labels: ready-for-review, web-ui

#1111 [CLI] Ensure TTL, timeout & thresholds are imported
  CHANGELOG.md
  cli/commands/importer/catalog/sensu-v1-misc.json
  cli/commands/importer/legacy.go
  cli/commands/importer/legacy_test.go
Labels: bug, ready-for-review

#1117 Govaluate's modifier tokens can now be optionally forbidden
  CHANGELOG.md
  types/asset.go
  types/check.go
  types/filter.go
  util/eval/eval.go
  util/eval/eval_test.go
Labels: ready-for-review

#1120 Add debug pprof endpoint
  CHANGELOG.md
  backend/cmd/start.go
Labels: ready-for-review

#1118 [Web UI] Simplify filtering events
  agent/assetmanager/asset.go
  backend/apid/graphql/environment.go
  backend/pipelined/filter.go
  backend/schedulerd/proxy_check.go
  dashboard/src/components/EventsContainer.js
  types/event.go
  types/event_test.go
  util/eval/predicate.go
  util/eval/predicate_test.go
Labels: ready-for-review

#1137 [GraphQL] Implement node resolver for events
  backend/apid/graphql/node.go
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  backend/apid/graphql/schema/event.gql.go
  backend/apid/graphql/schema/event.graphql
  backend/apid/graphql/schema/handler.gql.go
  backend/apid/graphql/schema/handler.graphql
  backend/apid/graphql/schema/hook.gql.go
  backend/apid/graphql/schema/hook.graphql
  backend/apid/graphql/schema/rbac.gql.go
  backend/apid/graphql/schema/rbac.graphql
Labels: ready-for-review, web-ui

#1140 Manage ulimits with systemd and sysvinit
  CHANGELOG.md
  packaging/services/sensu-agent/systemd/etc/systemd/system/sensu-agent.service
  packaging/services/sensu-agent/sysvinit/etc/init.d/sensu-agent
  packaging/services/sensu-backend/systemd/etc/systemd/system/sensu-backend.service
  packaging/services/sensu-backend/sysvinit/etc/init.d/sensu-backend
Labels: ready-for-review

#1139 Increase stack size on Travis CI for megacheck
  .travis.yml
  CHANGELOG.md
Labels: ready-for-review

#1144 Increase etcd default storage to 4GB.
  CHANGELOG.md
  backend/etcd/etcd.go
Labels: ready-for-review

#1134 Add custom functions to govaluate
  CHANGELOG.md
  util/eval/predicate.go
  util/eval/predicate_test.go
Labels: ready-for-review

#1141 Add cli support for CRUD mutators
  CHANGELOG.md
  cli/client/interface.go
  cli/client/mutator.go
  cli/client/testing/mock_mutator_client.go
  cli/commands/commands.go
  cli/commands/handler/interactive.go
  cli/commands/mutator/create.go
  cli/commands/mutator/create_test.go
  cli/commands/mutator/delete.go
  cli/commands/mutator/delete_test.go
  cli/commands/mutator/help.go
  cli/commands/mutator/info.go
  cli/commands/mutator/info_test.go
  cli/commands/mutator/interactive.go
  cli/commands/mutator/list.go
  cli/commands/mutator/list_test.go
  cli/commands/mutator/update.go
  cli/commands/mutator/update_test.go
  types/mutator.go
Labels: ready-for-review

#1138 Add issue template for GitHub
  .github/ISSUE_TEMPLATE.md
  CHANGELOG.md
Labels: ready-for-review

#1149 Move Hooks and Silenced into Check.
  CHANGELOG.md
  agent/check_handler.go
  backend/eventd/silenced.go
  backend/eventd/silenced_test.go
  backend/pipelined/filter_test.go
  backend/store/etcd/watchers_test.go
  cli/commands/event/list.go
  cli/commands/event/show.go
  testing/e2e/hooks_test.go
  testing/e2e/silencing_test.go
  types/check.pb.go
  types/check.proto
  types/event.go
  types/event_test.go
Labels: ready-for-review

#1146 [Web UI] Complete integration of events list
  CHANGELOG.md
  backend/apid/graphql/environment.go
  backend/apid/graphql/schema/environment.gql.go
  backend/apid/graphql/schema/environment.graphql
  backend/apid/graphql/service.go
  dashboard/package.json
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsContainerMenu.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/SearchBox.js
  dashboard/src/components/TableList/TableList.js
  dashboard/src/components/TableList/TableListEmptyState.js
  dashboard/src/components/TableList/TableListHeader.js
  dashboard/src/components/TableList/TableListItem.js
  dashboard/src/components/TableList/TableListSelect.js
  dashboard/src/components/TableList/index.js
  dashboard/src/index.js
  dashboard/src/pages/EventsPage.js
  dashboard/src/pages/GraphQLExplorerPage.js
  dashboard/src/routes.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1155 Don't set GOGC=off for lint jobs
  .travis.yml
  cli/commands/mutator/interactive.go
Labels: ready-for-review

#1154 Apid/put support
  CHANGELOG.md
  backend/apid/actions/assets.go
  backend/apid/actions/assets_test.go
  backend/apid/actions/checks.go
  backend/apid/actions/checks_test.go
  backend/apid/actions/environment.go
  backend/apid/actions/environment_test.go
  backend/apid/actions/events.go
  backend/apid/actions/events_test.go
  backend/apid/actions/filters.go
  backend/apid/actions/filters_test.go
  backend/apid/actions/handlers.go
  backend/apid/actions/handlers_test.go
  backend/apid/actions/hooks.go
  backend/apid/actions/hooks_test.go
  backend/apid/actions/mutators.go
  backend/apid/actions/mutators_test.go
  backend/apid/actions/organizations.go
  backend/apid/actions/organizations_test.go
  backend/apid/actions/roles.go
  backend/apid/actions/roles_test.go
  backend/apid/actions/silenced.go
  backend/apid/actions/silenced_test.go
  backend/apid/actions/users.go
  backend/apid/actions/users_test.go
  backend/apid/routers/assets.go
  backend/apid/routers/checks.go
  backend/apid/routers/entities.go
  backend/apid/routers/environments.go
  backend/apid/routers/events.go
  backend/apid/routers/filters.go
  backend/apid/routers/handlers.go
  backend/apid/routers/hooks.go
  backend/apid/routers/mutators.go
  backend/apid/routers/organizations.go
  backend/apid/routers/roles.go
  backend/apid/routers/routers.go
  backend/apid/routers/silenced.go
  backend/apid/routers/users.go
  cli/client/asset.go
  cli/client/check.go
  cli/client/client.go
  cli/client/entity.go
  cli/client/environment.go
  cli/client/filter.go
  cli/client/handler.go
  cli/client/hook.go
  cli/client/mutator.go
  cli/client/organization.go
  cli/client/silenced.go
Labels: ready-for-review

#1162 Bugfix/agentd sessions
  CHANGELOG.md
  backend/agentd/agentd.go
  backend/agentd/session.go
Labels: ready-for-review

#1167 Remove watcher tests.
  backend/store/etcd/watchers_test.go
Labels: ready-for-review

#1164 Only use one lease per ring
  backend/ring/ring.go
  backend/ring/ring_test.go
Labels: ready-for-review

#1166 Add benchmarking utility and add ability to disable API and Socket listeners in the agent
  CHANGELOG.md
  agent/agent.go
  agent/cmd/start.go
  benchmark/cmd/main.go
Labels: ready-for-review

#1169 Made the examples in CONTRIBUTING.md more obvious
  CHANGELOG.md
  CONTRIBUTING.md
Labels: ready-for-review

#1168 Use a package level cache for ring leases.
  backend/ring/ring.go
  backend/ring/ring_test.go
Labels: ready-for-review

#1151 [CLI] Do not swallow errors in list package
  cli/commands/asset/help.go
  cli/commands/asset/info.go
  cli/commands/asset/info_test.go
  cli/commands/check/help.go
  cli/commands/check/info.go
  cli/commands/check/info_test.go
  cli/commands/entity/help.go
  cli/commands/entity/info.go
  cli/commands/entity/info_test.go
  cli/commands/event/help.go
  cli/commands/event/info.go
  cli/commands/event/info_test.go
  cli/commands/filter/info.go
  cli/commands/handler/info.go
  cli/commands/hook/help.go
  cli/commands/hook/info.go
  cli/commands/hook/info_test.go
  cli/commands/silenced/info.go
  cli/commands/silenced/info_test.go
  cli/elements/list/list.go
  cli/elements/list/list_test.go
Labels: ready-for-review

#1152 [Web UI] Upgrade material-ui dependency to latest
  dashboard/package.json
  dashboard/src/components/Drawer.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/QuickNavButton.js
  dashboard/src/components/SearchBox.js
  dashboard/src/components/TableList/TableListButton.js
  dashboard/src/components/TableList/TableListEmptyState.js
  dashboard/src/components/TableList/TableListItem.js
  dashboard/src/components/TableList/TableListSelect.js
  dashboard/src/components/TableList/index.js
  dashboard/src/components/Toolbar.js
  dashboard/src/pages/EventsPage.js
  dashboard/src/routes.js
  dashboard/yarn.lock
  types/event.go
Labels: ready-for-review, web-ui

#1174 Handle round-robin scheduling through WizardBus.
  CHANGELOG.md
  backend/agentd/agentd.go
  backend/agentd/session.go
  backend/agentd/session_test.go
  backend/backend.go
  backend/eventd/eventd_test.go
  backend/eventd/integration_test.go
  backend/keepalived/integration_test.go
  backend/keepalived/keepalived_test.go
  backend/messaging/benchmark_test.go
  backend/messaging/message_bus.go
  backend/messaging/wizard_bus.go
  backend/messaging/wizard_bus_test.go
  backend/messaging/wizard_topic.go
  backend/pipelined/pipelined_test.go
  backend/ring/ring.go
  backend/schedulerd/check_scheduler.go
  backend/schedulerd/check_scheduler_test.go
  backend/schedulerd/executor_test.go
  backend/schedulerd/round_robin_scheduler.go
  backend/schedulerd/round_robin_scheduler_test.go
  backend/schedulerd/schedule_manager.go
  backend/schedulerd/schedulerd.go
  backend/schedulerd/schedulerd_test.go
  testing/mockbus/mock.go
Labels: ready-for-review

#1173 Add cli flag for environment variables
  CHANGELOG.md
  backend/apid/routers/mutators.go
  cli/commands/handler/create.go
  cli/commands/handler/create_test.go
  cli/commands/handler/interactive.go
  cli/commands/handler/list.go
  cli/commands/mutator/create.go
  cli/commands/mutator/create_test.go
  cli/commands/mutator/interactive.go
  cli/commands/mutator/list.go
Labels: ready-for-review

#1181 Add informational logging for entity keepalives
  CHANGELOG.md
  backend/keepalived/deregisterer.go
  backend/keepalived/keepalived.go
Labels: ready-for-review

#1142 Automatically create a "default" environment when creating a new organization
  CHANGELOG.md
  backend/apid/actions/organizations.go
  backend/apid/actions/organizations_test.go
  backend/schedulerd/schedulerd_test.go
  backend/seeds/seeds.go
  backend/store/etcd/helpers_test.go
  backend/store/etcd/organization_store.go
  backend/store/etcd/organization_store_test.go
  backend/store/etcd/store_test.go
  backend/store/store.go
  testing/e2e/rbac_test.go
  testing/mockstore/organizations.go
Labels: ready-for-review

#1171 Comment out descriptions of PR template headings
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-review

#1170 Fixed shutting down message to not include %s
  CHANGELOG.md
  backend/backend.go
Labels: ready-for-review

#1189 Don't use golint in the build process.
  build.sh
Labels: ready-for-review

#1180 Add missing LICENSE files.
  backend/apid/actions/LICENSE
  backend/apid/graphql/schema/LICENSE
  backend/apid/routers/LICENSE
  backend/dashboardd/LICENSE
  backend/etcd/LICENSE
  backend/leader/LICENSE
  backend/migration/LICENSE
  backend/monitor/LICENSE
  backend/queue/LICENSE
  backend/ring/LICENSE
  backend/seeds/LICENSE
  backend/store/etcd/testutil/LICENSE
  benchmark/cmd/LICENSE
  build.sh
  cli/commands/check/subcommands/LICENSE
  cli/commands/importer/LICENSE
  cli/commands/mutator/LICENSE
  cli/commands/silenced/LICENSE
  cli/commands/timeutil/LICENSE
  cli/elements/report/LICENSE
  dashboard/scripts/LICENSE
  graphql/LICENSE
  graphql/generator/LICENSE
  graphql/integration/LICENSE
  rpc/LICENSE
  scripts/LICENSE
  testing/mockmonitor/LICENSE
  testing/mockqueue/LICENSE
  testing/mockring/LICENSE
  testing/mocktransport/LICENSE
  types/dynamic/LICENSE
  types/v1/LICENSE
  util/eval/LICENSE
  util/retry/LICENSE
  util/time/LICENSE
Labels: ready-for-review

#1193 Updated etcd to 3.3.2
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  backend/etcd/etcd.go
Labels: ready-for-review

#1202 backend/eventd: don't double write events
  CHANGELOG.md
  backend/eventd/eventd.go
Labels: ready-for-review

#1190 Rework WizardBus Subscribe() method to remove subscriber ID
  CHANGELOG.md
  backend/agentd/session.go
  backend/eventd/eventd.go
  backend/eventd/integration_test.go
  backend/keepalived/integration_test.go
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
  backend/messaging/benchmark_test.go
  backend/messaging/message_bus.go
  backend/messaging/wizard_bus.go
  backend/messaging/wizard_bus_test.go
  backend/messaging/wizard_topic.go
  backend/pipelined/pipelined.go
  backend/schedulerd/check_scheduler_test.go
  backend/schedulerd/executor_test.go
  backend/schedulerd/schedulerd_test.go
  testing/mockbus/mock.go
Labels: ready-for-review

#1210 Add distinction between global & local flags in sensuctl usage
  CHANGELOG.md
  cli/cmd/cobra.go
  cli/cmd/start.go
Labels: ready-for-review

#1207 Logrus logging should accept field arguments
  CHANGELOG.md
  agent/agent.go
  agent/check_handler.go
  agent/sockets.go
  backend/agentd/agentd.go
  backend/agentd/session.go
  backend/apid/middlewares/allowlist.go
  backend/apid/middlewares/authentication.go
  backend/apid/middlewares/refresh_token.go
  backend/apid/routers/authentication.go
  backend/apid/routers/graphql.go
  backend/apid/routers/routers.go
  backend/backend.go
  backend/dashboardd/dashboardd.go
  backend/eventd/eventd.go
  backend/keepalived/deregisterer.go
  backend/keepalived/keepalived.go
  backend/migration/environments.go
  backend/pipelined/handle.go
  backend/pipelined/mutate.go
  backend/schedulerd/check_scheduler.go
  backend/schedulerd/executor.go
  backend/schedulerd/round_robin_scheduler.go
  backend/store/etcd/watchers.go
Labels: ready-for-review

#1198 [Web UI] Replace fileb0x
  .b0x.yaml
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  README.md
  backend/backend.go
  backend/cmd/start.go
  backend/dashboardd/ab0x.go
  backend/dashboardd/dashboardd.go
  backend/dashboardd/dashboardd_test.go
  build.ps1
  build.sh
  dashboard/.gitignore
  dashboard/assets.go
  dashboard/assets_dev.go
  dashboard/assets_generate.go
  dashboard/config/polyfills.js
  dashboard/config/webpack.config.prod.js
  dashboard/config/webpackDevServer.config.js
  dashboard/fallback.go
  dashboard/package.json
  dashboard/public/index.html
  dashboard/public/manifest.json
  dashboard/src/components/AppFrame.js
  dashboard/src/components/AppRoot.js
  dashboard/src/components/RestrictUnauthenticated.js
  dashboard/src/environment.js
  dashboard/src/pages/Login.js
  dashboard/src/pages/RootRedirect.js
  dashboard/src/routes.js
  dashboard/yarn.lock
Labels: ready-for-review

#1206 Fixup panic when resolving events
  backend/apid/apid.go
  backend/apid/graphql/mutations.go
  backend/apid/routers/events.go
  cli/client/event.go
Labels: bug, ready-for-review

#1197 Generate protobufs with go generate.
  CHANGELOG.md
  README.md
  scripts/check_protoc/LICENSE
  scripts/check_protoc/main.go
  scripts/genproto.sh
  types/types_gen.go
Labels: ready-for-review

#1201 Support adding rules to role on creation via cli.
  CHANGELOG.md
  cli/commands/role/create.go
  cli/commands/role/create_test.go
  testing/e2e/rbac_test.go
Labels: ready-for-review

#1219 Remove short description
  cli/cmd/start.go
Labels: ready-for-review

#1218 Nightly builds
  .gitignore
  .travis.yml
  CHANGELOG.md
  Makefile
  build.sh
  version/cmd/version/LICENSE
  version/cmd/version/version.go
  version/iteration.txt
  version/prerelease.txt
  version/sort.go
  version/sort_test.go
  version/version.go
  version/version_test.go
Labels: ready-for-review

#1220 Build version-bin in Makefile first-pass
  .travis.yml
  Makefile
  build.sh
Labels: ready-for-review

#1229 Re-encrypt gcs-service-account.json using travis-ci.org
  build.sh
  gcs-service-account.json.enc
Labels: ready-for-review

#1187 Add sensuctl create command
  CHANGELOG.md
  cli/client/generic.go
  cli/client/interface.go
  cli/client/testing/mock_generic.go
  cli/commands/commands.go
  cli/commands/create/LICENSE
  cli/commands/create/create.go
  cli/commands/create/create_test.go
  cli/commands/create/help.go
  scripts/make_typemap/LICENSE
  scripts/make_typemap/make_typemap.go
  types/adhoc.go
  types/asset.go
  types/check.go
  types/entity.go
  types/environment.go
  types/error.go
  types/event.go
  types/filter.go
  types/handler.go
  types/hook.go
  types/mutator.go
  types/organization.go
  types/resource.go
  types/silenced.go
  types/typemap.go
  types/typemap.tmpl
  types/types_gen.go
  types/wrapper.go
Labels: ready-for-review

#1236 Run go generate using host's GOOS & GOARCH
  Makefile
  build.sh
Labels: ready-for-review

#1231 Fix the manual packaging process
  CHANGELOG.md
  Dockerfile.packaging
  Makefile
Labels: ready-for-review

#1238 Use each port only once during e2e tests.
  testing/testutil/util.go
Labels: ready-for-review

#1211 Use the iconurl & username in slack handler
  CHANGELOG.md
  handlers/slack/main.go
Labels: ready-for-review

#1239 Nightly build fixes
  build-gcs-release.sh
  build.sh
Labels: ready-for-review

#1241 Avoid building nightly binaries for now
  build.sh
Labels: ready-for-review

#1227 Add extension support to apid.
  CHANGELOG.md
  backend/apid/actions/assets.go
  backend/apid/actions/checks.go
  backend/apid/actions/events.go
  backend/apid/actions/extensions.go
  backend/apid/actions/extensions_test.go
  backend/apid/actions/hooks.go
  backend/apid/actions/organizations.go
  backend/apid/actions/roles.go
  backend/apid/actions/silenced.go
  backend/apid/actions/users.go
  backend/apid/graphql/relay/node.go
  backend/apid/routers/extensions.go
  backend/authorization/extensions.go
  backend/store/etcd/extension_registry.go
  backend/store/etcd/extension_registry_test.go
  backend/store/store.go
  testing/mockstore/extension.go
  testing/testutil/context.go
  types/extension.go
  types/rbac.go
Labels: ready-for-review

#1225 Make the entire repository go-buildable.
  backend/apid/graphql/README.md
  graphql/integration/doc.go
  scripts/gengraphql/LICENSE
  scripts/gengraphql/gengraphql.go
  scripts/proto2graphql/LICENSE
  scripts/proto2graphql/proto2graphql.go
  testing/e2e/doc.go
Labels: ready-for-review

#1212 Improve communication around dashboard bundle failures
  build.sh
  dashboard/assets.go
  dashboard/assets_generate.go
Labels: ready-for-review

#1246 Properly log the event being handled in pipelined
  CHANGELOG.md
  backend/pipelined/handle.go
Labels: ready-for-review

#1243 Remove -c check flag
  CHANGELOG.md
  cli/commands/check/execute.go
Labels: ready-for-review

#1232 Add event filtering to extension proto.
  CHANGELOG.md
  rpc/extension.pb.go
  rpc/extension.proto
  rpc/rpc_gen.go
Labels: ready-for-review

#1242 Second stab at dealing with port collisions.
  testing/testutil/util.go
Labels: ready-for-review
