Repository sensu/sensu-go, pull requests merged in 2018-07, with the labels that each got.

#1771 Add dockerfile for rhel-atomic
  CHANGELOG.md
  Dockerfile.rhel
Labels: ready-for-review

#1773 Add line continuation to Dockerfile
  Dockerfile
Labels: ready-for-review

#1737 [Web UI] Checks page sorting and silencing
  dashboard/package.json
  dashboard/src/components/CheckList.js
  dashboard/src/components/CheckRow.js
  dashboard/src/components/controller/ListController.js
  dashboard/src/components/controller/MenuController.js
  dashboard/src/components/partials/ChecksList/ChecksList.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/ChecksList/index.js
  dashboard/src/components/partials/EntitiesList/EntitiesList.js
  dashboard/src/components/partials/EventsList/EventsList.js
  dashboard/src/components/partials/EventsList/EventsListHeader.js
  dashboard/src/components/partials/ListHeader/ListHeader.js
  dashboard/src/components/partials/ListHeader/index.js
  dashboard/src/components/partials/ListSortMenu/ListSortMenu.js
  dashboard/src/components/partials/ListSortMenu/index.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1782 Issue 1730, part 1
  .circleci/config.yml
Labels: ready-for-review

#1780 Clustering/round robin check ttl
  CHANGELOG.md
  backend/backend.go
  backend/eventd/eventd.go
  backend/eventd/eventd_test.go
  backend/eventd/integration_test.go
  backend/keepalived/integration_test.go
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
  backend/monitor/monitor.go
  backend/monitor/monitor_test.go
  backend/monitor/monitors_test.go
  backend/monitor/supervisor.go
  testing/mockmonitor/LICENSE
  testing/mockmonitor/monitor.go
Labels: ready-for-review

#1781 Docker changes
  CHANGELOG.md
  Dockerfile
  Dockerfile.rhel
  build.sh
  docker-compose.yaml
Labels: ready-for-review

#1799 Revert "Per Justin, stop building tools."
  .circleci/config.yml
Labels: ready-for-review

#1800 Fix format strings for --format help flag in sensuctl
  CHANGELOG.md
  cli/commands/helpers/flags.go
Labels: ready-for-review

#1798 Check execution test failures
  agent/check_handler_internal_test.go
Labels: ready-for-review

#1784 Refactoring of the Backend struct
  CHANGELOG.md
  backend/agentd/agentd.go
  backend/apid/apid.go
  backend/backend.go
  backend/backend_test.go
  backend/cmd/root.go
  backend/cmd/start.go
  backend/daemon/daemon.go
  backend/dashboardd/dashboardd.go
  backend/eventd/eventd.go
  backend/keepalived/keepalived.go
  backend/messaging/wizard_bus.go
  backend/pipelined/pipelined.go
  backend/schedulerd/schedulerd.go
  cmd/sensu-backend/main.go
  testing/mockbus/mock.go
Labels: ready-for-review

#1796 Remove check subdue e2e and unused variables/functions
  CHANGELOG.md
  testing/e2e/check_subdue_test.go
  testing/e2e/doc.go
  testing/e2e/main_test.go
  testing/e2e/process_test.go
Labels: ready-for-review

#1779 Skip host verification on loopback interface
  CHANGELOG.md
  backend/dashboardd/dashboardd.go
Labels: bug, ready-for-review

#1789 Use constants instead of hardcoded strings for all rules, all orgs, all envs #1285
  backend/apid/middlewares/environment_test.go
  backend/authorization/authorization.go
  backend/authorization/organizations.go
  backend/authorization/roles.go
  backend/seeds/seeds.go
  backend/store/etcd/environment_store.go
  backend/store/etcd/event_store.go
  backend/store/etcd/event_store_test.go
  backend/store/etcd/helpers.go
  backend/store/etcd/helpers_test.go
  cli/commands/asset/list.go
  cli/commands/check/list.go
  cli/commands/entity/list.go
  cli/commands/environment/list.go
  cli/commands/event/list.go
  cli/commands/filter/list.go
  cli/commands/handler/list.go
  cli/commands/hook/list.go
  cli/commands/mutator/list.go
  cli/commands/silenced/list.go
  types/environment.go
  types/organization.go
  types/rbac_test.go
Labels: ready-for-review

#1813 Add unit tests for environments and organizations.
  backend/apid/apid.go
  backend/apid/routers/environments.go
  backend/apid/routers/environments_test.go
  backend/apid/routers/organizations.go
  backend/apid/routers/organizations_test.go
  backend/apid/routers/routers_test.go
Labels: ready-for-review

#1793 Fix help output for "sensuctl config set-format --help"
  cli/commands/config/set_format.go
Labels: ready-for-review

#1820 Add unit test coverage for check routers
  CHANGELOG.md
  backend/apid/apid.go
  backend/apid/routers/checks.go
  backend/apid/routers/checks_test.go
Labels: ready-for-review

#1819 Bugfixes to the Backend refactoring
  backend/backend.go
  backend/cmd/start.go
Labels: ready-for-review

#1794 [Web UI] Complete checks list styles
  dashboard/src/components/Code.js
  dashboard/src/components/StatusListItem.js
  dashboard/src/components/TableList/TableList.js
  dashboard/src/components/TableList/TableListBody.js
  dashboard/src/components/TableList/TableListButton.js
  dashboard/src/components/TableList/TableListHeader.js
  dashboard/src/components/TableList/TableListItem.js
  dashboard/src/components/TableList/TableListSelect.js
  dashboard/src/components/TableList/index.js
  dashboard/src/components/partials/ButtonMenu/ButtonMenu.js
  dashboard/src/components/partials/ButtonMenu/index.js
  dashboard/src/components/partials/ChecksList/ChecksList.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/EntitiesList/EntitiesList.js
  dashboard/src/components/partials/EntitiesList/EntitiesListHeader.js
  dashboard/src/components/partials/EntitiesList/EntitiesListItem.js
  dashboard/src/components/partials/EventsList/EventsList.js
  dashboard/src/components/partials/EventsList/EventsListHeader.js
  dashboard/src/components/partials/EventsList/EventsListItem.js
  dashboard/src/components/partials/IconButton/IconButton.js
  dashboard/src/components/partials/IconButton/index.js
  dashboard/src/components/partials/ResourceDetails/ResourceDetails.js
  dashboard/src/components/partials/ResourceDetails/index.js
  dashboard/src/components/partials/StatusMenu.js
  dashboard/src/components/partials/TableOverflowCell/TableOverflowCell.js
  dashboard/src/components/partials/TableOverflowCell/index.js
  dashboard/src/components/partials/TableSelectableRow/TableSelectableRow.js
  dashboard/src/components/partials/TableSelectableRow/index.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
Labels: ready-for-review, web-ui

#1818 Use clustered sensu in docker-compose.yaml
  docker-compose.yaml
Labels: ready-for-review

#1822 Remove import command.
  CHANGELOG.md
  cli/commands/commands.go
  cli/commands/importer/LICENSE
  cli/commands/importer/catalog/sensu-v1-1-spec.json
  cli/commands/importer/catalog/sensu-v1-misc.json
  cli/commands/importer/cmd.go
  cli/commands/importer/cmd_test.go
  cli/commands/importer/importer.go
  cli/commands/importer/importer_test.go
  cli/commands/importer/legacy.go
  cli/commands/importer/legacy_test.go
  cli/commands/importer/util.go
Labels: ready-for-review

#1823 Adjust CHANGELOG per @majormoses
  CHANGELOG.md
Labels: ready-for-review

#1826 Improve TestExecuteCheck
  agent/check_handler_internal_test.go
Labels: ready-for-review

#1747 [Web UI] Adhoc check requests
  backend/apid/graphql/check.go
  backend/apid/graphql/check_test.go
  backend/apid/graphql/error.go
  backend/apid/graphql/mutations.go
  backend/apid/graphql/mutations_test.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/errors.gql.go
  backend/apid/graphql/schema/errors.graphql
  backend/apid/graphql/schema/mutations.gql.go
  backend/apid/graphql/schema/mutations.graphql
  backend/apid/graphql/service.go
  backend/apid/graphql/services.go
  backend/apid/graphql/services_test.go
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/components/partials/ChecksList/ChecksList.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsReRunAction.js
  dashboard/src/mutations/executeCheck.js
Labels: ready-for-review, web-ui

#1828 [Web UI] Allow check to be executed when no subscriptions are given
  backend/apid/graphql/schema/mutations.gql.go
  backend/apid/graphql/schema/mutations.graphql
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/mutations/executeCheck.js
Labels: ready-for-review, web-ui

#1824 Export apid router and resource routes
  backend/apid/apid.go
  backend/apid/routers/assets.go
  backend/apid/routers/checks.go
  backend/apid/routers/entities.go
  backend/apid/routers/environments.go
  backend/apid/routers/events.go
  backend/apid/routers/extensions.go
  backend/apid/routers/filters.go
  backend/apid/routers/handlers.go
  backend/apid/routers/hooks.go
  backend/apid/routers/mutators.go
  backend/apid/routers/organizations.go
  backend/apid/routers/roles.go
  backend/apid/routers/routers.go
  backend/apid/routers/silenced.go
  backend/apid/routers/users.go
Labels: ready-for-review

#1836 [GraphQL] Updates to CheckConfig type
  backend/apid/graphql/check.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/service.go
  backend/apid/graphql/timewindow.go
Labels: ready-for-review, web-ui

#1815 [Web UI] Silences Page
  backend/apid/graphql/environment.go
  backend/apid/graphql/schema/environment.gql.go
  backend/apid/graphql/schema/environment.graphql
  backend/apid/graphql/service.go
  dashboard/src/apollo/schema/client.graphql
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/apollo/stateLink.js
  dashboard/src/components/Drawer.js
  dashboard/src/components/QuickNav.js
  dashboard/src/components/controller/MenuController.js
  dashboard/src/components/controller/ModalController.js
  dashboard/src/components/partials/SilencesList/SilencesList.js
  dashboard/src/components/partials/SilencesList/SilencesListItem.js
  dashboard/src/components/partials/SilencesList/index.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
  dashboard/src/components/views/EnvironmentView/SilencesContent.js
  dashboard/src/icons/Check.js
  dashboard/src/icons/Entity.js
  dashboard/src/icons/Event.js
  dashboard/src/icons/Silence.js
  dashboard/src/mutations/deleteSilence.js
  types/silenced.go
  types/silenced_test.go
Labels: ready-for-review, web-ui

#1837 [GraphQL] Add check field to Query
  backend/apid/actions/checks.go
  backend/apid/graphql/query.go
  backend/apid/graphql/schema/schema.gql.go
  backend/apid/graphql/schema/schema.graphql
  backend/apid/graphql/service.go
Labels: ready-for-review

#1835 Properly tag and push the Docker nightly image
  CHANGELOG.md
  build.sh
Labels: ready-for-review

#1650 [GraphQL] Gracefully handle failed type assertions
  backend/apid/graphql/environment.go
  backend/apid/graphql/pagination.go
  backend/apid/graphql/schema/asset.gql.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/environment.gql.go
  backend/apid/graphql/schema/errors.gql.go
  backend/apid/graphql/schema/event.gql.go
  backend/apid/graphql/schema/handler.gql.go
  backend/apid/graphql/schema/hook.gql.go
  backend/apid/graphql/schema/mutations.gql.go
  backend/apid/graphql/schema/mutator.gql.go
  backend/apid/graphql/schema/namespace.gql.go
  backend/apid/graphql/schema/organization.gql.go
  backend/apid/graphql/schema/pagination.gql.go
  backend/apid/graphql/schema/rbac.gql.go
  backend/apid/graphql/schema/silenced.gql.go
  backend/apid/graphql/schema/subscriptions.gql.go
  backend/apid/graphql/schema/time_window.gql.go
  backend/apid/graphql/schema/user.gql.go
  graphql/generator/object.go
  graphql/resolvers.go
Labels: bug, ready-for-review

#1842 [Web UI] Fixup reversed arguments in MenuController
  dashboard/src/components/controller/MenuController.js
Labels: bug, ready-for-review, web-ui

#1843 Fixed a test failure by replacing TLS cert.
  CHANGELOG.md
  util/ssl/ca.pem
  util/ssl/etcd1-key.pem
  util/ssl/etcd1.pem
Labels: ready-for-review

#1840 Add API support for cluster management.
  CHANGELOG.md
  backend/apid/actions/cluster.go
  backend/apid/actions/cluster_test.go
  backend/apid/apid.go
  backend/apid/routers/cluster.go
  backend/apid/routers/cluster_test.go
  backend/authorization/cluster.go
  backend/backend.go
  types/rbac.go
Labels: ready-for-review

#1831 Re-work ring for round-robin check execution.
  CHANGELOG.md
  backend/messaging/wizard_bus.go
  backend/messaging/wizard_topic.go
  backend/ring/logger.go
  backend/ring/ring.go
  backend/ring/ring_test.go
  types/ring.go
Labels: ready-for-review

#1846 Refactoring of sensuctl main pkg
  CHANGELOG.md
  build.ps1
  build.sh
  cli/cmd/start.go
  cli/cmd/start_internal_test.go
  cli/commands/root/LICENSE
  cli/commands/root/root.go
  cli/commands/root/root_test.go
  cli/commands/root/templates.go
  cli/commands/version/LICENSE
  cli/commands/version/version.go
  cli/commands/version/version_test.go
  cmd/sensuctl/LICENSE
  cmd/sensuctl/main.go
Labels: ready-for-review

#1844 Add sensuctl cluster member-list command.
  CHANGELOG.md
  backend/apid/actions/cluster_test.go
  backend/authorization/cluster.go
  cli/client/cluster.go
  cli/client/interface.go
  cli/client/testing/mock_cluster_client.go
  cli/commands/cluster/LICENSE
  cli/commands/cluster/help.go
  cli/commands/cluster/member-list.go
  cli/commands/commands.go
  cli/commands/helpers/print.go
Labels: ready-for-review

#1851 Issue 1730, part 2
  .circleci/config.yml
Labels: ready-for-review

#1859 Export GetWatcherAction function for use by sensu-enterprise-go
  backend/store/etcd/watchers.go
Labels: ready-for-review

#1850 Add sensuctl cluster member-add command.
  CHANGELOG.md
  cli/client/cluster.go
  cli/client/interface.go
  cli/client/testing/mock_cluster_client.go
  cli/commands/cluster/help.go
  cli/commands/cluster/member-add.go
  cli/commands/cluster/member-add_test.go
Labels: ready-for-review

#1857 Issue 1730: Tools (and related infra) to start posting CircleCI artifacts to S3
  .circleci/config.yml
  build/ci/circle-ci-setup.sh
Labels: ready-for-review

#1863 Introduce Sensu edition detection in sensuctl
  CHANGELOG.md
  cli/client/authentication.go
  cli/client/authentication_test.go
  cli/client/config/basic/basic.go
  cli/client/config/basic/reader.go
  cli/client/config/basic/reader_test.go
  cli/client/config/basic/writer.go
  cli/client/config/basic/writer_test.go
  cli/client/config/config.go
  cli/client/interface.go
  cli/client/testing/mock_authentication_client.go
  cli/client/testing/mock_config.go
  cli/commands/configure/configure.go
  cli/commands/root/templates.go
  cli/commands/user/change_password.go
  types/edition.go
Labels: ready-for-review

#1864 Export store within the backend
  backend/authorization/authorization.go
  backend/authorization/authorization_test.go
  backend/backend.go
Labels: ready-for-review

#1865 Add sensuctl cluster member-remove command.
  cli/client/cluster.go
  cli/client/interface.go
  cli/client/testing/mock_cluster_client.go
  cli/commands/cluster/help.go
  cli/commands/cluster/member-remove.go
  cli/commands/cluster/member-update.go
Labels: ready-for-review

#1871 Add support for licensing in API client
  CHANGELOG.md
  cli/client/client.go
  cli/client/interface.go
  cli/client/license.go
  cli/client/testing/mock_license_client.go
Labels: ready-for-review

#1873 Expose some CLI helpers
  cli/client/check.go
  cli/client/cluster.go
  cli/client/entity.go
  cli/client/error.go
  cli/client/event.go
  cli/client/hook.go
  cli/client/mutator.go
  cli/client/role.go
  cli/client/silenced.go
  cli/client/user.go
  cli/commands/create/create.go
  cli/commands/helpers/input.go
Labels: ready-for-review

#1877 Upgrade dep to v0.5.0
  CHANGELOG.md
  Gopkg.lock
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
  vendor/github.com/ulikunitz/xz/cmd/gxz/licenses.go
  vendor/github.com/ulikunitz/xz/cmd/xb/copyright.go
Labels: ready-for-review

#1875 Cluster health
  CHANGELOG.md
  backend/apid/actions/health.go
  backend/apid/apid.go
  backend/apid/routers/status.go
  backend/apid/routers/status_test.go
  backend/etcd/etcd.go
  backend/etcd/etcd_test.go
  backend/store/etcd/health_store.go
  backend/store/etcd/health_store_test.go
  backend/store/store.go
  testing/mockstore/health.go
  types/status_map.go
Labels: ready-for-review

#1874 Add edition header to middleware and build scripts
  CHANGELOG.md
  backend/apid/apid.go
  backend/apid/middlewares/edition.go
  build.ps1
  build.sh
  version/version.go
Labels: ready-for-review

#1876 [Web UI] Clear silences
  backend/apid/graphql/check.go
  backend/apid/graphql/check_test.go
  backend/apid/graphql/entity.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  dashboard/package.json
  dashboard/src/apollo/schema/client.graphql
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/apollo/stateLink.js
  dashboard/src/components/ButtonSet/ButtonSet.js
  dashboard/src/components/CheckStatusIcon/CheckStatusIcon.js
  dashboard/src/components/DialogContentParagraph/DialogContentParagraph.js
  dashboard/src/components/DialogContentParagraph/index.js
  dashboard/src/components/Preferences.js
  dashboard/src/components/RelativeDate/RelativeDate.js
  dashboard/src/components/partials/ChecksList/ChecksList.js
  dashboard/src/components/partials/ChecksList/ChecksListHeader.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/ClearSilencedEntriesDialog/Dialog.js
  dashboard/src/components/partials/ClearSilencedEntriesDialog/index.js
  dashboard/src/components/partials/CollapsingMenu/CollapsingMenu.js
  dashboard/src/components/partials/CollapsingMenu/SubMenu.js
  dashboard/src/components/partials/EntitiesList/EntitiesList.js
  dashboard/src/components/partials/EntitiesList/EntitiesListHeader.js
  dashboard/src/components/partials/EntitiesList/EntitiesListItem.js
  dashboard/src/components/partials/EventsList/EventsList.js
  dashboard/src/components/partials/EventsList/EventsListHeader.js
  dashboard/src/components/partials/EventsList/EventsListItem.js
  dashboard/src/components/partials/LiveButton/LiveButton.js
  dashboard/src/components/partials/LiveButton/index.js
  dashboard/src/components/partials/ResourceDetails/ResourceDetails.js
  dashboard/src/components/partials/SilenceExpiration/SilenceExpiration.js
  dashboard/src/components/partials/SilenceExpiration/index.js
  dashboard/src/components/partials/SilencesList/SilencesListItem.js
  dashboard/src/components/partials/TableSelectableRow/TableSelectableRow.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/mutations/deleteCheck.js
  dashboard/src/polyfill.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1880 Do not use build flags for the Sensu edition
  build.ps1
  build.sh
  version/version.go
Labels: ready-for-review

#1881 Add CircleCI build status badge.
  README.md
Labels: ready-for-review

#1884 Remove unused golint from build
  build.ps1
  build.sh
Labels: ready-for-review

#1848 [Web UI] Create check details view
  backend/apid/graphql/check.go
  backend/apid/graphql/handler.go
  backend/apid/graphql/hook.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  dashboard/package.json
  dashboard/src/apollo/schema/client.graphql
  dashboard/src/apollo/stateLink.js
  dashboard/src/components/Code.js
  dashboard/src/components/Monospaced/Monospaced.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsContainer.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsDeleteAction.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsExecuteAction.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsUnsilenceAction.js
  dashboard/src/components/partials/CheckDetailsContainer/index.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/ClearSilencedEntriesDialog/Dialog.js
  dashboard/src/components/partials/CronDescriptor/CronDescriptor.js
  dashboard/src/components/partials/CronDescriptor/index.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
  dashboard/src/components/partials/ListHeader/ListHeader.js
  dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui
