Repository sensu/sensu-go, pull requests merged in 2018-08, with the labels that each got.

#1892 Add a deadline to extension methods.
  rpc/extension_executor.go
Labels: ready-for-review

#1900 [Web UI] Properly parse events in minified builds
  dashboard/package.json
  dashboard/yarn.lock
Labels: bug, ready-for-review, web-ui

#1912 [Web UI] Use pre-packaged instead of referencing repo
  dashboard/package.json
  dashboard/yarn.lock
Labels: bug, ready-for-review, web-ui

#1895 Gracefully handle type assertions in cli
  CHANGELOG.md
  cli/cli.go
  cli/commands/asset/list.go
  cli/commands/check/list.go
  cli/commands/cluster/health.go
  cli/commands/cluster/member-list.go
  cli/commands/cluster/member-remove.go
  cli/commands/entity/list.go
  cli/commands/environment/list.go
  cli/commands/event/list.go
  cli/commands/extension/list.go
  cli/commands/filter/list.go
  cli/commands/handler/list.go
  cli/commands/hook/list.go
  cli/commands/mutator/list.go
  cli/commands/organization/list.go
  cli/commands/role/list.go
  cli/commands/role/list_rules.go
  cli/commands/silenced/list.go
  cli/commands/user/list.go
Labels: ready-for-review

#1891 Remove code duplication from newCLI() func
  cli/commands/asset/info_test.go
  cli/commands/asset/list_test.go
  cli/commands/check/info_test.go
  cli/commands/check/list_test.go
  cli/commands/cluster/health_test.go
  cli/commands/entity/info_test.go
  cli/commands/entity/list_test.go
  cli/commands/extension/list_test.go
  cli/commands/filter/info_test.go
  cli/commands/filter/list_test.go
  cli/commands/handler/list_test.go
  cli/commands/hook/info_test.go
  cli/commands/hook/list_test.go
  cli/commands/mutator/info_test.go
  cli/commands/mutator/list_test.go
  cli/commands/organization/list_test.go
  cli/commands/role/list_rules_test.go
  cli/commands/role/list_test.go
  cli/commands/silenced/info_test.go
  cli/commands/silenced/list_test.go
  cli/commands/testing/cli.go
  cli/commands/user/list_test.go
Labels: ready-for-review

#1902 [Web UI] Silence form bugfixes
  backend/apid/graphql/mutations.go
  backend/apid/graphql/silenced.go
  dashboard/src/components/RelativeDate/RelativeDate.js
  dashboard/src/components/partials/SilenceEntryForm/SilenceEntryForm.js
  dashboard/src/components/partials/SilencesList/SilencesListItem.js
  types/event.go
  types/event_test.go
Labels: bug, ready-for-review, web-ui

#1910 [Web UI] Use cron value in check list
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsContainer.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/CronDescriptor/CronDescriptor.js
  dashboard/src/components/partials/EventsList/EventsListItem.js
  dashboard/src/components/partials/TableSelectableRow/TableSelectableRow.js
Labels: bug, ready-for-review, web-ui

#1914 Add a newline after asset creation confirmation
  cli/commands/asset/create.go
Labels: ready-for-review

#1917 Update changelog with 2.0.0-beta.3-1 release
  CHANGELOG.md
Labels: ready-for-review

#1916 Prevent empty subscriptions in agentd
  CHANGELOG.md
  backend/agentd/session.go
Labels: ready-for-review

#1894 Improve Sensu edition header handling
  CHANGELOG.md
  cli/client/authentication.go
  cli/client/authentication_test.go
  cli/client/client.go
  cli/client/interface.go
  cli/client/testing/mock_authentication_client.go
  cli/commands/config/view.go
  cli/commands/config/view_test.go
  cli/commands/configure/configure.go
  cli/commands/user/change_password.go
Labels: ready-for-review

#1897 RBAC bugfixes
  CHANGELOG.md
  backend/authorization/authorization.go
  backend/authorization/authorization_test.go
  cli/commands/role/add_rule.go
  cli/commands/role/create.go
  cli/commands/role/help.go
  cli/commands/role/info.go
  cli/commands/role/info_test.go
  types/rbac.go
Labels: ready-for-review

#1922 Silence usage on startup
  CHANGELOG.md
  agent/cmd/start.go
  backend/cmd/start.go
Labels: ready-for-review

#1923 Use default value for splay_coverage in sensuctl
  CHANGELOG.md
  cli/commands/check/subcommands/set_proxy_request.go
  cli/commands/check/subcommands/set_proxy_request_test.go
Labels: ready-for-review

#1911 Set issued & history on keepalive events
  CHANGELOG.md
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
Labels: ready-for-review

#1929 Resolve panic in sensuctl cluster health
  CHANGELOG.md
  backend/store/etcd/health_store.go
Labels: ready-for-review

#1930 Add agent ID and IP address to agentd session logs
  CHANGELOG.md
  backend/agentd/agentd.go
  backend/agentd/session.go
Labels: ready-for-review

#1915 [Web UI] Tweaks & minor fixes for issues found in QA session
  dashboard/src/components/AppContent.js
  dashboard/src/components/ButtonIcon/ButtonIcon.js
  dashboard/src/components/Content/Content.js
  dashboard/src/components/CurrentDateProvider/CurrentDateProvider.js
  dashboard/src/components/CurrentDateProvider/index.js
  dashboard/src/components/Preferences.js
  dashboard/src/components/RelativeDate/RelativeDate.js
  dashboard/src/components/RelativeDate/RelativeToCurrentDate.js
  dashboard/src/components/RelativeDate/index.js
  dashboard/src/components/partials/ButtonMenu/Button.js
  dashboard/src/components/partials/ButtonMenu/ButtonMenu.js
  dashboard/src/components/partials/ButtonMenu/Menu.js
  dashboard/src/components/partials/ButtonMenu/index.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsContainer.js
  dashboard/src/components/partials/ChecksList/ChecksListHeader.js
  dashboard/src/components/partials/CollapsingMenu/Button.js
  dashboard/src/components/partials/CollapsingMenu/CollapsingMenu.js
  dashboard/src/components/partials/CollapsingMenu/SubMenu.js
  dashboard/src/components/partials/EntitiesList/EntitiesListHeader.js
  dashboard/src/components/partials/EntitiesList/EntitiesListItem.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsContainer.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsEvents.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
  dashboard/src/components/partials/EventsList/EventsListHeader.js
  dashboard/src/components/partials/EventsList/EventsListItem.js
  dashboard/src/components/partials/IconButton/IconButton.js
  dashboard/src/components/partials/IconButton/index.js
  dashboard/src/components/partials/ListHeader/ListHeader.js
  dashboard/src/components/partials/RelatedEntitiesCard/RelatedEntitiesCard.js
  dashboard/src/components/partials/SilenceExpiration/SilenceExpiration.js
  dashboard/src/components/partials/SilencesList/SilencesList.js
  dashboard/src/components/partials/SilencesList/SilencesListItem.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/EnvironmentView/SilencesContent.js
  dashboard/src/icons/Unsilence.js
  dashboard/src/themes/defaults.js
  dashboard/src/themes/dva.js
  dashboard/src/themes/index.js
Labels: ready-for-review, web-ui

#1939 Dockerfile: add etcdctl
  Dockerfile
Labels: ready-for-review

#1943 Correct README getting started Docker image repo and tag
  README.md
Labels: ready-for-review

#1940 Bump gopsutil to v2.18.07 and wmi to b12b22c
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/StackExchange/wmi/README.md
  vendor/github.com/StackExchange/wmi/swbemservices.go
  vendor/github.com/StackExchange/wmi/wmi.go
  vendor/github.com/shirou/gopsutil/README.rst
  vendor/github.com/shirou/gopsutil/disk/disk.go
  vendor/github.com/shirou/gopsutil/disk/disk_darwin.go
  vendor/github.com/shirou/gopsutil/disk/disk_freebsd.go
  vendor/github.com/shirou/gopsutil/disk/disk_linux.go
  vendor/github.com/shirou/gopsutil/disk/disk_openbsd.go
  vendor/github.com/shirou/gopsutil/disk/disk_unix.go
  vendor/github.com/shirou/gopsutil/host/host_linux.go
  vendor/github.com/shirou/gopsutil/host/host_windows.go
  vendor/github.com/shirou/gopsutil/internal/common/common.go
  vendor/github.com/shirou/gopsutil/mem/mem.go
  vendor/github.com/shirou/gopsutil/mem/mem_linux.go
  vendor/github.com/shirou/gopsutil/mem/mem_windows.go
  vendor/github.com/shirou/gopsutil/net/net.go
  vendor/github.com/shirou/gopsutil/net/net_unix.go
  vendor/github.com/shirou/gopsutil/process/process_fallback.go
  vendor/github.com/shirou/gopsutil/process/process_linux.go
  vendor/github.com/shirou/gopsutil/process/process_posix.go
  vendor/github.com/shirou/gopsutil/process/process_windows.go
Labels: ready-for-review

#1945 build.[sh|ps1] deps command no longer exists
  .appveyor.yml
  .travis.yml
Labels: ready-for-review

#1889 Testing/timeproxy
  Gopkg.lock
  Gopkg.toml
  backend/schedulerd/check_scheduler_test.go
  backend/schedulerd/check_timer.go
  backend/schedulerd/check_timer_test.go
  backend/schedulerd/executor.go
  backend/schedulerd/executor_test.go
  backend/schedulerd/proxy_check.go
  backend/schedulerd/schedulerd_test.go
  backend/schedulerd/testutil_test.go
  backend/schedulerd/timeproxy_test.go
  vendor/github.com/echlebek/crock/LICENSE
  vendor/github.com/echlebek/crock/README.md
  vendor/github.com/echlebek/crock/doc.go
  vendor/github.com/echlebek/crock/ticker.go
  vendor/github.com/echlebek/crock/time.go
  vendor/github.com/echlebek/crock/timer.go
  vendor/github.com/echlebek/crock/types.go
  vendor/github.com/echlebek/timeproxy/.gitignore
  vendor/github.com/echlebek/timeproxy/LICENSE
  vendor/github.com/echlebek/timeproxy/doc.go
  vendor/github.com/echlebek/timeproxy/time.go
Labels: ready-for-review

#1946 Remove deps & lint steps in Circle CI
  .circleci/config.yml
Labels: ready-for-review

#1941 Fixup redirect loop encountered when backend is missing dashboard
  dashboard/fallback.go
Labels: ready-for-review

#1948 InfluxDB metric transformer allows the 3rd timestamp argument to be optional
  CHANGELOG.md
  agent/transformers/influx_db.go
  agent/transformers/influx_db_test.go
Labels: ready-for-review

#1942 Re-work queue to support one-to-many messaging.
  CHANGELOG.md
  backend/backend.go
  backend/etcd/etcd.go
  backend/etcd/sequence.go
  backend/etcd/sequence_test.go
  backend/queue/queue.go
  backend/queue/queue_test.go
  backend/ring/ring.go
  backend/ring/ring_test.go
Labels: ready-for-review

#1958 [Web UI] Redirect to user to last visited environment
  dashboard/src/apollo/client.js
  dashboard/src/apollo/localStorageSync.js
  dashboard/src/apollo/resolvers/lastEnvironment.js
  dashboard/src/apollo/schema/client.graphql
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/apollo/stateLink.js
  dashboard/src/components/AppRoot.js
  dashboard/src/components/ExteriorWrapper.js
  dashboard/src/components/createStyledComponent/createStyledComponent.js
  dashboard/src/components/createStyledComponent/index.js
  dashboard/src/components/partials/SigninDialog/SigninDialog.js
  dashboard/src/components/partials/SigninDialog/SigninForm.js
  dashboard/src/components/partials/SigninDialog/index.js
  dashboard/src/components/util/DefaultRedirect.js
  dashboard/src/components/util/LastEnvironmentRedirect.js
  dashboard/src/components/util/LastEnvironmentUpdater.js
  dashboard/src/components/util/SigninRedirect.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
  dashboard/src/components/views/SignInView.js
  dashboard/src/constants/queryParams.js
  dashboard/src/icons/SensuIcon.js
  dashboard/src/icons/SensuLogo.js
Labels: ready-for-review, web-ui

#1962 Bugfix for sensuctl cluster health error handling
  CHANGELOG.md
  backend/store/etcd/health_store.go
Labels: ready-for-review

#1977 Move changelog entry to unreleased
  CHANGELOG.md
Labels: ready-for-review

#1980 Update archiver sha to fix git tarball bug
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/mholt/archiver/tar.go
Labels: ready-for-review

#1981 Fix the changelog entries to unreleased
  CHANGELOG.md
Labels: ready-for-review

#1984 [Web UI] Fixup exception when deleting checks
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsDeleteAction.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsDeleteAction.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsDeleteAction.js
Labels: ready-for-review, web-ui

#1985 [Web UI] Update to patched @10xjs/form release
  dashboard/package.json
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#2001 Add windows/386 support to build-gcs-release.sh
  CHANGELOG.md
  build-gcs-release.sh
Labels: ready-for-review

#2004 [Agent] Use absolute path when obtaining lockfile
  CHANGELOG.md
  agent/assetmanager/asset.go
Labels: ready-for-review, web-ui

#1996 Close extension grpc client conns after execution.
  backend/pipelined/filter.go
  backend/pipelined/handle.go
  backend/pipelined/handle_test.go
  backend/pipelined/mutate.go
  rpc/extension_executor.go
Labels: ready-for-review

#2013 [CLI] Use terminals configured default text colour
  CHANGELOG.md
  cli/elements/globals/colors.go
  cli/elements/table/standard.go
Labels: ready-for-review, sensuctl
