Repository sensu/sensu-go, pull requests merged in 2018-04, with the labels that each got.

#1256 Revert build.sh docker changes from b7dbfdf8; rm node_modules in build.sh
  build.sh
Labels: ready-for-review

#1244 Add statsd server to sensu-agent and log metrics
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  agent/agent.go
  agent/cmd/start.go
  agent/statsd_server.go
  agent/statsd_server_test.go
  backend/agentd/session.go
Labels: ready-for-review

#1251 Backout/port experiment
  testing/testutil/util.go
Labels: ready-for-review

#1265 Fix a deadlock in the monitor.
  backend/monitor/monitor.go
Labels: ready-for-review

#1266 Terminate processes gracefully in e2e tests
  CHANGELOG.md
  testing/e2e/agent_reconnection_test.go
  testing/e2e/keepalive_test.go
  testing/e2e/process_test.go
  testing/e2e/rbac_test.go
Labels: ready-for-review

#1273 Updated readme for new users
  README.md
Labels: ready-for-review

#1274 Use lowercase sensitive "github.com/sirupsen/logrus"
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  agent/agent.go
  agent/assetmanager/logger.go
  agent/cmd/start.go
  agent/debug_test.go
  agent/logger.go
  agent/statsd_server.go
  backend/agentd/logger.go
  backend/agentd/session.go
  backend/apid/actions/actions_test.go
  backend/apid/graphql/globalid/register.go
  backend/apid/graphql/logger.go
  backend/apid/graphql/relay/logger.go
  backend/apid/graphql/relay/node.go
  backend/apid/logger.go
  backend/apid/middlewares/allowlist.go
  backend/apid/middlewares/logger.go
  backend/apid/middlewares/logging.go
  backend/apid/middlewares/refresh_token.go
  backend/apid/routers/logger.go
  backend/authorization/authorization.go
  backend/cmd/logger.go
  backend/dashboardd/dashboardd.go
  backend/debug_test.go
  backend/etcd/logger.go
  backend/etcd/logrus_formatter.go
  backend/eventd/eventd.go
  backend/keepalived/logger.go
  backend/leader/integration_test.go
  backend/leader/logging.go
  backend/leader/supervisor.go
  backend/logger.go
  backend/migration/migration.go
  backend/pipelined/filter.go
  backend/pipelined/handle.go
  backend/pipelined/logger.go
  backend/pipelined/mutate.go
  backend/queue/logger.go
  backend/schedulerd/check_scheduler.go
  backend/schedulerd/debug_test.go
  backend/schedulerd/executor.go
  backend/schedulerd/logger.go
  backend/seeds/logger.go
  backend/store/etcd/debug_test.go
  backend/store/etcd/logger.go
  backend/store/etcd/logrus_formatter.go
  cli/cli.go
  cli/client/client.go
  cli/client/config/basic/basic.go
  cli/commands/importer/importer.go
  cli/commands/importer/legacy_test.go
  cli/elements/report/report.go
  cli/elements/report/report_test.go
  cli/elements/report/writer.go
  command/command.go
  graphql/generator/logger.go
  scripts/gengraphql/gengraphql.go
Labels: ready-for-review

#1275 Improved README installation guide formatting
  README.md
Labels: ready-for-review

#1268 Make wizardbus synchronous
  CHANGELOG.md
  backend/keepalived/keepalived.go
  backend/messaging/wizard_bus.go
  backend/messaging/wizard_bus_test.go
  backend/messaging/wizard_topic.go
  backend/pipelined/handle.go
  backend/schedulerd/check_scheduler_test.go
Labels: ready-for-review

#1277 http_check.sh hides its output
  CHANGELOG.md
  examples/checks/http_check.sh
Labels: ready-for-review

#1272 Add extensions to pipelined
  CHANGELOG.md
  backend/backend.go
  backend/pipelined/filter.go
  backend/pipelined/filter_test.go
  backend/pipelined/handle.go
  backend/pipelined/handle_test.go
  backend/pipelined/mutate.go
  backend/pipelined/mutate_test.go
  backend/pipelined/pipelined.go
  rpc/extension_executor.go
  rpc/extension_executor_test.go
Labels: ready-for-review

#1281 Prevent app from crashing with expired refresh token
  dashboard/src/pages/RootRedirect.js
Labels: ready-for-review

#1282 Prevent dev build from halting on lint error
  dashboard/config/webpack.config.dev.js
Labels: ready-for-review

#1286 Create default read-only user
  CHANGELOG.md
  backend/authorization/authorization.go
  backend/seeds/seeds.go
  backend/seeds/seeds_test.go
Labels: ready-for-review

#1288 Provide a means of configuring event handlers for metrics
  CHANGELOG.md
  agent/agent.go
  agent/cmd/start.go
  agent/statsd_server.go
Labels: ready-for-review

#1289 [Web UI] Migrate from Relay to Apollo
  dashboard/.eslintrc.yml
  dashboard/.gitignore
  dashboard/data/.gitkeep
  dashboard/package.json
  dashboard/scripts/updateSchema.go
  dashboard/src/apollo/client.js
  dashboard/src/components/AppBar.js
  dashboard/src/components/AppFrame.js
  dashboard/src/components/AppWrapper.js
  dashboard/src/components/CheckList.js
  dashboard/src/components/CheckRow.js
  dashboard/src/components/Drawer.js
  dashboard/src/components/EnvironmentIcon/EnvironmentIcon.js
  dashboard/src/components/EnvironmentLabel/EnvironmentLabel.js
  dashboard/src/components/EnvironmentSymbol/EnvironmentSymbol.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/NamespaceLink.js
  dashboard/src/components/NamespaceSelector.js
  dashboard/src/components/NamespaceSelectorMenu.js
  dashboard/src/components/OrganizationIcon/OrganizationIcon.js
  dashboard/src/environment.js
  dashboard/src/index.js
  dashboard/src/mutations/ResolveEventMutation.js
  dashboard/src/pages/ChecksPage.js
  dashboard/src/pages/EventsPage.js
  dashboard/src/pages/GraphQLExplorerPage.js
  dashboard/src/routes.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1290 [GraphQL] Snip extra value from environment id
  backend/apid/graphql/globalid/environments.go
  backend/apid/graphql/globalid/environments_test.go
Labels: ready-for-review

#1283 [Agent statsd] Additional unit and integration tests
  CHANGELOG.md
  agent/statsd_server.go
  agent/statsd_server_test.go
Labels: ready-for-review

#1293 fix sensuapp.org -> sensu.io
  README.md
Labels: ready-for-review

#1297 [GraphQL] Expose an environment's check history
  backend/apid/graphql/check.go
  backend/apid/graphql/check_test.go
  backend/apid/graphql/environment.go
  backend/apid/graphql/environment_test.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/environment.gql.go
  backend/apid/graphql/schema/environment.graphql
  backend/apid/graphql/util.go
Labels: ready-for-review

#1296 [GraphQL] Expose related entities using simple heuristic
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_test.go
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  util/strings/strings.go
  util/strings/strings_test.go
Labels: ready-for-review

#1307 [GraphQL] Add hook, silenced, lastOK & occurrences fields to Check
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
Labels: ready-for-review, web-ui

#1294 Option to configure statsd listener with statsd-disable flag
  CHANGELOG.md
  agent/agent.go
  agent/cmd/start.go
Labels: ready-for-review

#1305 Add extension package and extension example.
  CHANGELOG.md
  rpc/extension/LICENSE
  rpc/extension/doc.go
  rpc/extension/example/LICENSE
  rpc/extension/example/main.go
  rpc/extension/extension.go
  rpc/extension/server.go
Labels: ready-for-review

#1317 [Web UI] Retrieve any stored tokens during the initial load
  dashboard/src/utils/authentication/index.js
  dashboard/src/utils/authentication/tokens.js
Labels: ready-for-review, web-ui

#1316 [Web UI] Create more thorough global style reset
  dashboard/public/index.html
  dashboard/src/components/BrowserOverrides.js
  dashboard/src/components/ResetStyles.js
  dashboard/src/components/ThemeStyles.js
  dashboard/src/index.js
  dashboard/src/reset.css.js
Labels: ready-for-review, web-ui

#1314 Initial README get started
  README.md
Labels: ready-for-review

#1306 Optimize check marshaling and add a benchmark for subPump
  CHANGELOG.md
  backend/agentd/benchmark_test.go
  backend/agentd/session.go
  types/check.go
Labels: ready-for-review

#1322 [Web UI] Wrap apollo client initialization in function
  dashboard/src/apollo/client.js
  dashboard/src/index.js
Labels: ready-for-review, web-ui

#1326 Populate Issued field for Check and CheckRequest.
  CHANGELOG.md
  agent/check_handler.go
  agent/check_handler_internal_test.go
  backend/schedulerd/executor.go
  backend/schedulerd/executor_test.go
  types/check.pb.go
  types/check.proto
  types/check_test.go
  types/typemap.go
  types/types_gen.go
Labels: ready-for-review

#1311 Add log level config to the backend and agent.
  CHANGELOG.md
  agent/cmd/start.go
  backend/cmd/logger.go
  backend/cmd/start.go
Labels: ready-for-review

#1325 Send statsd metric events through the pipeline
  CHANGELOG.md
  agent/statsd_server.go
  agent/statsd_server_test.go
  backend/agentd/session.go
  backend/eventd/eventd.go
  backend/pipelined/filter.go
  backend/pipelined/handle.go
  types/event.go
Labels: ready-for-review

#1292 [Web UI] Switch to React Router v4
  dashboard/.eslintrc.yml
  dashboard/package.json
  dashboard/src/components/AppBar.js
  dashboard/src/components/AppFrame.js
  dashboard/src/components/AppRoot.js
  dashboard/src/components/AppWrapper.js
  dashboard/src/components/Drawer.js
  dashboard/src/components/DrawerButton.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/NamespaceLink.js
  dashboard/src/components/NamespaceSelector.js
  dashboard/src/components/NamespaceSelectorBuilder.js
  dashboard/src/components/NamespaceSelectorMenu.js
  dashboard/src/components/QuickNav.js
  dashboard/src/components/QuickNavButton.js
  dashboard/src/components/RestrictUnauthenticated.js
  dashboard/src/components/util/AuthenticatedRoute.js
  dashboard/src/components/util/ConditionalRoute.js
  dashboard/src/components/util/DefaultRedirect.js
  dashboard/src/components/util/UnauthenticatedRoute.js
  dashboard/src/components/util/withAuthTokens.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/DashboardContent.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/EnvironmentView/index.js
  dashboard/src/components/views/LoginView.js
  dashboard/src/components/views/NotFoundView.js
  dashboard/src/index.js
  dashboard/src/pages/RootRedirect.js
  dashboard/src/reducer/reducer.js
  dashboard/src/routes.js
  dashboard/src/store/createStore.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1327 Optimize dynamic unmarshaling
  .gitignore
  CHANGELOG.md
  backend/agentd/benchmark_test.go
  backend/agentd/session.go
  transport/transport.go
  types/benchmark_test.go
  types/dynamic/dynamic.go
  types/dynamic/encoding.go
  types/dynamic/encoding_test.go
  types/dynamic/util.go
  types/dynamic/util_test.go
  types/hook.go
Labels: ready-for-review

#1334 [GraphQL] Change return type of issued field
  backend/apid/graphql/check.go
  backend/apid/graphql/check_test.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
Labels: ready-for-review, web-ui

#1335 [GraphQL] Change return type of LastOK field
  backend/apid/graphql/check.go
  backend/apid/graphql/check_test.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
Labels: ready-for-review, web-ui

#1332 [GraphQL] Add TTL field to check type
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
Labels: ready-for-review, web-ui

#1333 [GraphQL] Add timeout field to check type
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
Labels: ready-for-review, web-ui

#1331 Silenced entries with an asterisk in their ID can be deleted
  CHANGELOG.md
  backend/apid/actions/silenced.go
  backend/apid/actions/silenced_test.go
  backend/apid/routers/silenced.go
  testing/e2e/silencing_test.go
  testing/mockstore/silenced.go
Labels: ready-for-review

#1346 Default statsd flush interval
  CHANGELOG.md
  agent/statsd_server.go
Labels: ready-for-review

#1338 [Web UI] Create Loader component
  dashboard/package.json
  dashboard/src/components/AnimatedLogo.js
  dashboard/src/components/AppBar.js
  dashboard/src/components/AppFrame.js
  dashboard/src/components/CheckList.js
  dashboard/src/components/Drawer.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/Loader.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1349 Fix agent flag value
  agent/cmd/start.go
Labels: ready-for-review

#1337 Add filters time windows management in sensuctl
  CHANGELOG.md
  backend/apid/actions/filters.go
  cli/commands/filter/help.go
  cli/commands/filter/subcommands/LICENSE
  cli/commands/filter/subcommands/remove_when.go
  cli/commands/filter/subcommands/remove_when_test.go
  cli/commands/filter/subcommands/set_when.go
  cli/commands/filter/subcommands/set_when_test.go
  types/filter.go
Labels: ready-for-review

#1354 Make sensu-{backend,agent} sysvinit compat for centos 6 family
  packaging/services/sensu-agent/sysvinit/etc/init.d/sensu-agent
  packaging/services/sensu-backend/sysvinit/etc/init.d/sensu-backend
Labels: ready-for-review

#1365 Workaround for golint 404 issue
  build.sh
Labels: ready-for-review

#1366 Revert golint workaround
  build.sh
Labels: ready-for-review

#1344 [GraphQL] Change return type lastSeen field
  backend/apid/graphql/check.go
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_test.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  graphql/generator/object.go
Labels: ready-for-review, web-ui

#1363 [Web UI] Avoid relative imports with module-resolver plugin
  dashboard/.babelrc
  dashboard/.eslintrc.yml
  dashboard/package.json
  dashboard/src/apollo/client.js
  dashboard/src/components/AppBar.js
  dashboard/src/components/AppFrame.js
  dashboard/src/components/AppRoot.js
  dashboard/src/components/AppThemeProvider.js
  dashboard/src/components/AppWrapper.js
  dashboard/src/components/CheckList.js
  dashboard/src/components/Drawer.js
  dashboard/src/components/EnvironmentIcon/EnvironmentIconBase.js
  dashboard/src/components/EnvironmentLabel/EnvironmentLabelBase.js
  dashboard/src/components/EnvironmentSymbol/EnvironmentSymbolBase.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/ExteriorWrapper.js
  dashboard/src/components/Loader.js
  dashboard/src/components/NamespaceSelector.js
  dashboard/src/components/NamespaceSelectorMenu.js
  dashboard/src/components/OrganizationIcon/OrganizationIconBase.js
  dashboard/src/components/QuickNav.js
  dashboard/src/components/ResetStyles.js
  dashboard/src/components/ThemeProvider.js
  dashboard/src/components/util/AuthenticatedRoute.js
  dashboard/src/components/util/DefaultRedirect.js
  dashboard/src/components/util/UnauthenticatedRoute.js
  dashboard/src/components/util/withAuthTokens.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/DashboardContent.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/LoginView.js
  dashboard/src/index.js
  dashboard/src/themes/Bubblegum.js
  dashboard/src/themes/Sensu.js
  dashboard/src/themes/bubblegum.js
  dashboard/src/themes/classic.js
  dashboard/src/themes/createTheme.js
  dashboard/src/themes/dva.js
  dashboard/src/themes/sensu.js
  dashboard/src/themes/uchiwa.js
  dashboard/src/utils/authentication/tokens.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1368 [Web UI] Disable query polling on checks and events pages
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
Labels: ready-for-review, web-ui

#1371 Prevent etcd client goroutine leaks in queue tests
  backend/queue/queue_test.go
Labels: ready-for-review

#1352 [Web UI] Use apollo-link-state for client-side auth state
  dashboard/.eslintrc.yml
  dashboard/src/apollo/authLink.js
  dashboard/src/apollo/client.js
  dashboard/src/apollo/errorLink.js
  dashboard/src/apollo/httpLink.js
  dashboard/src/apollo/localStorageSync.js
  dashboard/src/apollo/resolvers/auth.js
  dashboard/src/apollo/stateLink.js
  dashboard/src/components/Drawer.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/util/AuthenticatedRoute.js
  dashboard/src/components/util/DefaultRedirect.js
  dashboard/src/components/util/UnauthenticatedRoute.js
  dashboard/src/components/util/withAuthTokens.js
  dashboard/src/components/views/LoginView.js
  dashboard/src/mutations/createTokens.js
  dashboard/src/mutations/invalidateTokens.js
  dashboard/src/mutations/refreshTokens.js
  dashboard/src/mutations/resolveEvent.js
  dashboard/src/utils/authAPI.js
  dashboard/src/utils/authentication/index.js
  dashboard/src/utils/authentication/index.test.js
  dashboard/src/utils/authentication/requests.js
  dashboard/src/utils/authentication/storage.js
  dashboard/src/utils/authentication/storage.test.js
  dashboard/src/utils/authentication/tokens.js
  dashboard/src/utils/authentication/tokens.test.js
  dashboard/src/utils/date.js
Labels: ready-for-review, web-ui

#1339 [GraphQL] Fixup bug where env could not found
  backend/apid/graphql/query.go
  backend/apid/graphql/query_test.go
Labels: ready-for-review, web-ui

#1351 [GraphQL] Expose entity status
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_test.go
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  backend/apid/graphql/util.go
Labels: ready-for-review, web-ui

#1343 [Web UI] Display Check Results
  dashboard/config/polyfills.js
  dashboard/package.json
  dashboard/src/colors/cyberGrape.js
  dashboard/src/components/AppContent.js
  dashboard/src/components/CardHighlight/CardHighlight.js
  dashboard/src/components/CardHighlight/index.js
  dashboard/src/components/CheckStatusIcon/CheckStatusIcon.js
  dashboard/src/components/CheckStatusIcon/index.js
  dashboard/src/components/Content/Content.js
  dashboard/src/components/Content/index.js
  dashboard/src/components/DateFormatter/DateFormatter.js
  dashboard/src/components/DateFormatter/DateStringFormatter.js
  dashboard/src/components/DateFormatter/DateTime.js
  dashboard/src/components/DateFormatter/KitchenTime.js
  dashboard/src/components/DateFormatter/index.js
  dashboard/src/components/DetailedListItem/DetailedListItem.js
  dashboard/src/components/DetailedListItem/DetailedListItemSubtitle.js
  dashboard/src/components/DetailedListItem/DetailedListItemTitle.js
  dashboard/src/components/DetailedListItem/index.js
  dashboard/src/components/Dictionary/Dictionary.js
  dashboard/src/components/Dictionary/DictionaryEntry.js
  dashboard/src/components/Dictionary/DictionaryKey.js
  dashboard/src/components/Dictionary/DictionaryValue.js
  dashboard/src/components/Dictionary/index.js
  dashboard/src/components/Duration/Duration.js
  dashboard/src/components/Duration/index.js
  dashboard/src/components/EventStatus.js
  dashboard/src/components/EventsContainer.js
  dashboard/src/components/EventsListItem.js
  dashboard/src/components/Maybe/Maybe.js
  dashboard/src/components/Maybe/index.js
  dashboard/src/components/Monospaced/Monospaced.js
  dashboard/src/components/Monospaced/index.js
  dashboard/src/components/PlaceholderCard.js
  dashboard/src/components/RelativeDate/RelativeDate.js
  dashboard/src/components/RelativeDate/index.js
  dashboard/src/components/views/EnvironmentView/DashboardContent.js
  dashboard/src/components/views/EnvironmentView/EnvironmentView.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent/EventDetailsCheckResult.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent/EventDetailsConfiguration.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent/EventDetailsRelatedEntities.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent/index.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/icons/ErrorHollow.js
  dashboard/src/icons/SmallCheck.js
  dashboard/src/icons/WarnHollow.js
  dashboard/src/index.js
  dashboard/src/themes/defaults.js
  dashboard/src/themes/dva.js
  dashboard/src/utils/checkStatus.js
  dashboard/src/utils/consecutivePairs.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#1370 Allow checks and hooks to escape zombie processes that have timed out
  CHANGELOG.md
  agent/check_handler.go
  agent/hook.go
  agent/hook_test.go
  command/command.go
Labels: ready-for-review

#1376 Install golang dependencies in build.sh
  CHANGELOG.md
  build.sh
Labels: ready-for-review

#1374 Ensure that handlers and subscriptions are not null.
  CHANGELOG.md
  types/check.go
  types/check_test.go
Labels: ready-for-review

#1336 InfluxDB Handler
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  build.ps1
  build.sh
  handlers/influx-db/LICENSE
  handlers/influx-db/main.go
  handlers/influx-db/main_test.go
Labels: feature, ready-for-review

#1350 [GraphQL] Omit source from related entities
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_test.go
Labels: ready-for-review, web-ui

#1380 Pin dep version to 4.1.
  .appveyor.yml
  .travis.yml
  README.md
  build.ps1
  build.sh
Labels: ready-for-review

#1364 Disable gostatsd internal metric collection
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  agent/statsd_server.go
  agent/statsd_server_test.go
Labels: ready-for-review

#1393 Don't run statsd_server tests on appveyor
  agent/statsd_server_test.go
Labels: ready-for-review

#1391 Support for Check/CheckConfig metric_format and metric_handlers
  CHANGELOG.md
  backend/apid/actions/checks.go
  types/check.go
  types/check.pb.go
  types/check.proto
  types/check_test.go
Labels: ready-for-review

#1400 Remove reference to iteration.txt as it doesn't exist anymore
  build.ps1
Labels: ready-for-review
