Repository sensu/sensu-go, pull requests merged in 2018-10, with the labels that each got.

#2134 Issue 2121-Post build/test logs as artifacts to S3
  .circleci/config.yml
  build/ci/circle-ci-setup.sh
Labels: continuous integration, ready-for-review

#2140 Issue-2119: Remove CircleCI branch restrictions.
  .circleci/config.yml
Labels: ready-for-review

#2141 Create a "release" build_and_test job that fires on release tags.
  .circleci/config.yml
Labels: ready-for-review

#2142 Issue 2119, part 3
  .circleci/config.yml
Labels: ready-for-review

#2115 Mock out command execution
  .appveyor.yml
  .circleci/config.yml
  .travis.yml
  CHANGELOG.md
  agent/agent.go
  agent/check_handler.go
  agent/check_handler_internal_test.go
  agent/hook.go
  agent/hook_test.go
  backend/pipelined/handle.go
  backend/pipelined/handle_test.go
  backend/pipelined/mutate.go
  backend/pipelined/pipelined.go
  build.ps1
  build.sh
  command/command.go
  command/command_test.go
  command/util.go
  testing/mockexecutor/LICENSE
  testing/mockexecutor/executor.go
  tools/cat/LICENSE
  tools/cat/main.go
  tools/false/LICENSE
  tools/false/main.go
  tools/sleep/LICENSE
  tools/sleep/main.go
  tools/true/LICENSE
  tools/true/main.go
Labels: ready-for-review

#2149 Fix some Go 1.11 issues.
  CHANGELOG.md
  agent/token.go
  backend/monitor/supervisor.go
  backend/queue/queue_test.go
Labels: ready-for-review, review

#2150 [Web UI] Drop in replacement for Apollo's Query component
  dashboard/package.json
  dashboard/src/components/util/Query.js
  dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/EnvironmentView/SilencesContent.js
  dashboard/yarn.lock
Labels: bug, ready-for-review, review, web-ui

#2158 Add the meta and rbac packages.
  Gopkg.lock
  NOTICE
  hack/update-protobuf-boilerplate.txt
  hack/update-protobuf.sh
  internal/apis/meta/generated.pb.go
  internal/apis/meta/generated.proto
  internal/apis/meta/meta.go
  internal/apis/meta/meta_test.go
  internal/apis/meta/time.go
  internal/apis/meta/time_proto.go
  internal/apis/meta/time_test.go
  internal/apis/meta/types.go
  internal/apis/rbac/generated.pb.go
  internal/apis/rbac/generated.proto
  internal/apis/rbac/helpers.go
  internal/apis/rbac/helpers_test.go
  internal/apis/rbac/types.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/LICENSE
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/doc.go
  vendor/github.com/google/gofuzz/fuzz.go
Labels: ready-for-review, review

#2164 Devel/storage ng
  runtime/codec/codec.go
  runtime/codec/json/codec.go
  runtime/codec/protobuf/codec.go
  runtime/object.go
  storage/etcd/etcd.go
  storage/etcd/etcd_test.go
  storage/interfaces.go
Labels: ready-for-review, review

#2159 Attempt to fix TestPeriodicKeepalive()
  agent/agent_test.go
  agent/timeproxy_test.go
Labels: ready-for-review, review

#2169 Per issue 2118, decommission TravisCI.
  .travis.yml
Labels: ready-for-review, review

#2168 Remove the Error store & type
  CHANGELOG.md
  backend/store/etcd/error_store.go
  backend/store/etcd/error_store_test.go
  backend/store/store.go
  scripts/check_protoc/main.go
  testing/mockstore/errors.go
  types/adhoc.pb.go
  types/any.pb.go
  types/asset.pb.go
  types/authentication.pb.go
  types/check.pb.go
  types/entity.pb.go
  types/environment.pb.go
  types/error.go
  types/error.pb.go
  types/error.proto
  types/error_test.go
  types/errorpb_test.go
  types/event.pb.go
  types/extension.pb.go
  types/filter.pb.go
  types/handler.pb.go
  types/hook.pb.go
  types/keepalive.pb.go
  types/metrics.pb.go
  types/mutator.pb.go
  types/organization.pb.go
  types/rbac.pb.go
  types/silenced.pb.go
  types/time_window.pb.go
  types/tls.pb.go
  types/typemap.go
  types/types_gen.go
  types/user.pb.go
Labels: ready-for-review, review

#2171 Fine tune mock time for CI
  agent/agent_test.go
  agent/timeproxy_test.go
Labels: ready-for-review, review

#2174 Bump CircleCI resource_class to medium+
  .circleci/config.yml
Labels: ready-for-review, review

#2132 Refactor agent to use boltdb-based asset manager
  CHANGELOG.md
  agent/agent.go
  agent/agent_test.go
  agent/api_test.go
  agent/asset.go
  agent/assetmanager/asset.go
  agent/assetmanager/asset_test.go
  agent/assetmanager/factory.go
  agent/assetmanager/fixtures/LICENSE
  agent/assetmanager/fixtures/rubby-on-rails.tar
  agent/assetmanager/fixtures/rubby-on-rails.tgz
  agent/assetmanager/helpers_test.go
  agent/assetmanager/logger.go
  agent/assetmanager/manager.go
  agent/assetmanager/manager_test.go
  agent/assetmanager/set.go
  agent/assetmanager/set_test.go
  agent/assetmanager/store.go
  agent/assetmanager/store_test.go
  agent/check_handler.go
  agent/check_handler_env_test_unix.go
  agent/check_handler_env_test_windows.go
  agent/check_handler_internal_test.go
  agent/hook_test.go
  agent/sockets_test.go
  agent/statsd_server_test.go
  asset/LICENSE
  asset/asset.go
  asset/boltdb_manager.go
  asset/filtered_manager.go
  asset/filtered_manager_test.go
  asset/integration_test.go
  asset/set.go
  asset/set_test.go
  backend/queue/logger.go
  backend/queue/queue.go
  backend/schedulerd/check_scheduler_test.go
Labels: ready-for-review

#2185 fmt.Errorf cleanup
  agent/api.go
  agent/token.go
  asset/fetcher.go
  backend/agentd/entity.go
  backend/apid/apid.go
  backend/apid/routers/authentication.go
  backend/backend.go
  backend/dashboardd/dashboardd.go
  backend/keepalived/deregisterer.go
  cmd/sensu-agent/main.go
  cmd/sensu-backend/main.go
  types/dynamic/redact.go
  util/eval/predicate.go
Labels: ready-for-review, review

#2186 Add freeze-api conversion utility.
  internal/astutil/kind.go
  internal/cmd/freeze-api/convert.go
  internal/cmd/freeze-api/copy.go
  internal/cmd/freeze-api/main.go
  internal/cmd/gen-register/main.go
  internal/registry/registry.go
  runtime/registry/registry_gen.go
Labels: ready-for-review, review

#2170 RequestInfo middleware
  Gopkg.lock
  Gopkg.toml
  backend/apid/apid.go
  backend/apid/middlewares/request_info.go
  backend/apid/middlewares/request_info_test.go
  types/context.go
  types/request_info.go
  vendor/github.com/gorilla/mux/.travis.yml
  vendor/github.com/gorilla/mux/ISSUE_TEMPLATE.md
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/gorilla/mux/test_helpers.go
Labels: ready-for-review, review

#2189 Add the make call to build bits+packages back to CircleCI config.
  .circleci/config.yml
Labels: ready-for-review, review

#2188 Add Groups for User
  backend/apid/actions/users.go
  backend/apid/graphql/schema/user.gql.go
  backend/apid/graphql/schema/user.graphql
  backend/apid/routers/users.go
  backend/seeds/seeds.go
  cli/client/interface.go
  cli/client/testing/mock_user_client.go
  cli/client/user.go
  cli/commands/user/add_group.go
  cli/commands/user/add_group_test.go
  cli/commands/user/create.go
  cli/commands/user/create_test.go
  cli/commands/user/help.go
  cli/commands/user/list.go
  cli/commands/user/remove_group.go
  cli/commands/user/remove_group_test.go
  cli/commands/user/remove_groups.go
  cli/commands/user/remove_groups_test.go
  cli/commands/user/set_groups.go
  cli/commands/user/set_groups_test.go
  types/user.pb.go
  types/user.proto
Labels: ready-for-review, review

#2182 Implement handler/mutator assets
  CHANGELOG.md
  agent/agent.go
  agent/check_handler.go
  asset/filtered_manager.go
  asset/filtered_manager_test.go
  asset/logger.go
  asset/manager.go
  asset/store.go
  asset/store_test.go
  backend/apid/actions/handlers.go
  backend/apid/actions/mutators.go
  backend/backend.go
  backend/backend_test.go
  backend/cmd/start.go
  backend/config.go
  backend/pipelined/handle.go
  backend/pipelined/mutate.go
  backend/pipelined/pipelined.go
  cli/commands/handler/create.go
  cli/commands/handler/info.go
  cli/commands/handler/interactive.go
  cli/commands/handler/list.go
  cli/commands/mutator/create.go
  cli/commands/mutator/info.go
  cli/commands/mutator/interactive.go
  cli/commands/mutator/list.go
  packaging/files/backend.yml.example
  packaging/files/windows/backend.yml.example
  testing/e2e/process_test.go
  types/entity.go
  types/handler.pb.go
  types/handler.proto
  types/mutator.go
  types/mutator.pb.go
  types/mutator.proto
Labels: ready-for-review, review

#2203 Update changelog with release tag
  CHANGELOG.md
Labels: ready-for-review, review

#2211 Update to patched `react-resize-observer`
  dashboard/package.json
  dashboard/yarn.lock
Labels: ready-for-review, review

#2209 Setup new RBAC model in authorization middleware
  backend/apid/actions/cluster_test.go
  backend/apid/actions/generic.go
  backend/apid/actions/health.go
  backend/apid/actions/util.go
  backend/apid/apid.go
  backend/apid/middlewares/allowlist_test.go
  backend/apid/middlewares/authentication.go
  backend/apid/middlewares/authentication_test.go
  backend/apid/middlewares/authorization.go
  backend/apid/middlewares/authorization_attributes.go
  backend/apid/middlewares/authorization_attributes_test.go
  backend/apid/middlewares/authorization_test.go
  backend/apid/middlewares/refresh_token_test.go
  backend/apid/middlewares/request_info.go
  backend/apid/routers/authentication.go
  backend/apid/routers/authentication_test.go
  backend/apid/routers/rbac.go
  backend/authentication/jwt/jwt.go
  backend/authentication/jwt/jwt_test.go
  backend/authorization/interface.go
  backend/authorization/rbac/LICENSE
  backend/authorization/rbac/rbac.go
  backend/authorization/rbac/rbac_test.go
  backend/backend.go
  backend/eventd/integration_test.go
  backend/keepalived/integration_test.go
  backend/schedulerd/executor_test.go
  backend/schedulerd/schedulerd_test.go
  backend/seeds/seeds.go
  backend/seeds/seeds_test.go
  backend/store/etcd/testutil/store.go
  backend/store/etcd/token_store_test.go
  backend/store/etcd/user_store_test.go
  cli/commands/check/execute_test.go
  testing/mockstore/v2/LICENSE
  testing/mockstore/v2/mockstore.go
  types/context.go
  types/request_info.go
  types/token.go
  types/typemap.go
Labels: ready-for-review, review

#2212 Add RESTKey and StorageKey types
  storage/key.go
  storage/key_test.go
Labels: ready-for-review, review

#2172 [Web UI] Clear filter button
  dashboard/src/components/SearchBox/SearchBox.js
Labels: ready-for-review, review, web-ui

#2162 [Web UI] Check details page improvements
  CHANGELOG.md
  dashboard/.eslintrc.yml
  dashboard/config/webpack.config.js
  dashboard/package.json
  dashboard/src/components/Code.js
  dashboard/src/components/CodeBlock/CodeBlock.js
  dashboard/src/components/CodeBlock/index.js
  dashboard/src/components/CodeHighlight/CodeHighlight.js
  dashboard/src/components/CodeHighlight/CodeHighlight.worker.js
  dashboard/src/components/Dictionary/DictionaryValue.js
  dashboard/src/components/Monospaced/index.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsConfiguration.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsPublishAction.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsToolbar.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsUnpublishAction.js
  dashboard/src/components/partials/ChecksList/ChecksListItem.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsInformation.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#2220 Update changelog with beta 7
  CHANGELOG.md
Labels: ready-for-review, review

#2218 Remove tcp handler from sensu-go
  testing/tcphandler/LICENSE
  testing/tcphandler/main.go
Labels: ready-for-review, review

#2234 [Web-UI] Fix date input bug surfaced by React 16.4
  CHANGELOG.md
  dashboard/package.json
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#2236 Adjust APIVersion field when converting types.
  internal/apis/rbac/converters_v1alpha1_generated.go
  internal/apis/rbac/converters_v1alpha1_generated_test.go
  internal/cmd/freeze-api/convert.go
Labels: ready-for-review, review

#2235 [Web UI] Sort order fixes
  CHANGELOG.md
  backend/apid/graphql/environment.go
  backend/apid/graphql/schema/mutations.gql.go
  dashboard/src/components/partials/ListSortSelector/Menu.js
Labels: ready-for-review, review, web-ui

#2245 Keepalive bugfixes
  CHANGELOG.md
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
  backend/monitor/supervisor.go
  types/event.go
Labels: ready-for-review, review

#2264 Improve agent statsd log
  CHANGELOG.md
  agent/statsd_server.go
Labels: ready-for-review, review

#2238 [Web UI] Add links for entities and checks to events page
  CHANGELOG.md
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js
  dashboard/src/components/util/NamespaceLink.js
Labels: ready-for-review, web-ui
