Repository sensu/sensu-go, pull requests merged in 2019-06, with the labels that each got.

#3016 Optimize proxy check scheduling (proxy entity filtering)
  CHANGELOG.md
  backend/schedulerd/entity_cache.go
  backend/schedulerd/entity_cache_integration_test.go
  backend/schedulerd/entity_cache_test.go
  backend/schedulerd/executor.go
  backend/schedulerd/proxy_check.go
  backend/schedulerd/proxy_check_test.go
  js/js.go
  js/js_test.go
Labels: performance

#3028 [Graphql] Simple autosuggestion
  CHANGELOG.md
  backend/apid/graphql/query.go
  backend/apid/graphql/query_test.go
  backend/apid/graphql/schema/asset.gql.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/event.gql.go
  backend/apid/graphql/schema/handler.gql.go
  backend/apid/graphql/schema/hook.gql.go
  backend/apid/graphql/schema/mutator.gql.go
  backend/apid/graphql/schema/query.gql.go
  backend/apid/graphql/schema/query.graphql
  backend/apid/graphql/schema/resource.gql.go
  backend/apid/graphql/schema/schema.gql.go
  backend/apid/graphql/schema/schema.graphql
  backend/apid/graphql/schema/silenced.gql.go
  backend/apid/graphql/schema/suggest.gql.go
  backend/apid/graphql/schema/suggest.graphql
  backend/apid/graphql/service.go
  backend/apid/graphql/suggest.go
  backend/apid/graphql/suggest/field.go
  backend/apid/graphql/suggest/field_test.go
  backend/apid/graphql/suggest/parse.go
  backend/apid/graphql/suggest/parse_test.go
  backend/apid/graphql/suggest/register.go
  backend/apid/graphql/suggest/register_test.go
  backend/apid/graphql/suggest/resource.go
  backend/apid/graphql/suggest/resource_test.go
  types/wrapper.go
  types/wrapper_test.go
Labels: feature, ready-for-review

#3051 [GraphQL] Add ability to hook into initialization of service
  backend/apid/graphql/service.go
  backend/apid/graphql/service_test.go
  graphql/service.go
Labels: enhancement

#3090 [GraphQL] Return nil when no mutator is present on handler
  backend/apid/graphql/handler.go
  backend/apid/graphql/handler_test.go
Labels: bug
