Repository sensu/sensu-go, pull requests merged in 2019-04, with the labels that each got.

#2844 Added more verbose logging for proxy requests
  CHANGELOGS/unreleased/2799-proxy-request-logging.md
  backend/schedulerd/proxy_check.go
Labels: ready-for-review

#2848 Implement the ring for tessend
  CHANGELOGS/unreleased/2793-tessen-ring.md
  api/core/v2/tessen.go
  backend/backend.go
  backend/ringv2/ringv2.go
  backend/tessend/tessend.go
  backend/tessend/tessend_test.go
  docker-compose.yaml
Labels: ready-for-review

#2856 Remove test case for removed method
  backend/apid/graphql/silenced_test.go
Labels: regression, testing

#2847 [GraphQL] Add generic put mutation
  CHANGELOGS/unreleased/2847-add-put-mutation.md
  backend/apid/graphql/error.go
  backend/apid/graphql/mutations.go
  backend/apid/graphql/mutations_test.go
  backend/apid/graphql/node.go
  backend/apid/graphql/schema/errors.graphql
  backend/apid/graphql/schema/mutations.gql.go
  backend/apid/graphql/schema/mutations.graphql
  backend/apid/graphql/service.go
  graphql/service.go
Labels: ready-for-review

#2849 [GraphQL] Query for wrapped resource
  CHANGELOGS/unreleased/2849-add-wrapped-field.md
  backend/apid/graphql/query.go
  backend/apid/graphql/schema/schema.gql.go
  backend/apid/graphql/schema/schema.graphql
Labels: ready-for-review, web-ui

#2875 [GraphQL] Ensures that all types are registered
  graphql/integration/service_test.go
  graphql/integration/testdata/schema-kitchen-sink.gql.go
  graphql/integration/testdata/schema-kitchen-sink.graphql
  graphql/service.go
Labels: regression, web-ui

#2885 [Dashboardd] Proxy path /api
  backend/dashboardd/dashboardd.go
Labels: web-ui
