Repository sensu/sensu-go, pull requests merged in 2019-03, with the labels that each got.

#2744 [Web UI] Add additional info to event details page
  CHANGELOG.md
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckSummary.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsEntitySummary.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
Labels: ready-for-review, web-ui

#2740 Add package ringv2
  backend/etcd/sequence.go
  backend/etcd/sequence_test.go
  backend/ringv2/LICENSE
  backend/ringv2/interface.go
  backend/ringv2/ringv2.go
  backend/ringv2/ringv2_test.go
Labels: ready-for-review

#2746 Don't set a timeout for asset downloads
  CHANGELOGS/unreleased/2745-bugfix_asset_fetcher.md
  asset/fetcher.go
Labels: ready-for-review

#2737 Fix yaml and wrapped-json output for sensuctl user list
  CHANGELOG.md
  api/core/v2/user.go
  cli/commands/helpers/yaml.go
  cli/commands/user/list.go
  cli/commands/user/list_test.go
Labels: ready-for-review

#2768 Remove edition header
  CHANGELOGS/unreleased/2767-edition-header.md
  api/core/v2/edition.go
  backend/apid/apid.go
  backend/apid/middlewares/edition.go
  cli/client/client.go
  cli/client/config/basic/basic.go
  cli/client/config/basic/reader.go
  cli/client/config/basic/reader_test.go
  cli/client/config/basic/writer.go
  cli/client/config/basic/writer_test.go
  cli/client/config/config.go
  cli/client/config/inmemory/inmemory.go
  cli/client/testing/mock_config.go
  cli/commands/config/view.go
  cli/commands/config/view_test.go
  version/version.go
Labels: ready-for-review

#2754 Split agent subscriptions properly in CLI flags
  CHANGELOGS/unreleased/2735-entity-subscription-bugfix.md
  agent/cmd/start.go
Labels: ready-for-review

#2766 Rework round robin
  CHANGELOGS/unreleased/2699-round-robin-scheduling.md
  backend/agentd/agentd.go
  backend/agentd/benchmark_test.go
  backend/agentd/session.go
  backend/agentd/session_test.go
  backend/backend.go
  backend/etcd/sequence.go
  backend/etcd/sequence_test.go
  backend/eventd/eventd_test.go
  backend/eventd/integration_test.go
  backend/keepalived/integration_test.go
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
  backend/messaging/benchmark_test.go
  backend/messaging/message_bus.go
  backend/messaging/wizard_bus.go
  backend/messaging/wizard_bus_test.go
  backend/messaging/wizard_topic.go
  backend/pipelined/pipelined_test.go
  backend/ring/LICENSE
  backend/ring/logger.go
  backend/ring/ring.go
  backend/ring/ring_test.go
  backend/ringv2/LICENSE
  backend/ringv2/interface.go
  backend/ringv2/pool.go
  backend/ringv2/pool_test.go
  backend/ringv2/ringv2.go
  backend/ringv2/ringv2_test.go
  backend/schedulerd/check_scheduler.go
  backend/schedulerd/check_scheduler_test.go
  backend/schedulerd/check_scheduler_unit_test.go
  backend/schedulerd/check_watcher.go
  backend/schedulerd/check_watcher_test.go
  backend/schedulerd/cron_scheduler.go
  backend/schedulerd/entity_cache.go
  backend/schedulerd/entity_cache_integration_test.go
  backend/schedulerd/entity_cache_test.go
  backend/schedulerd/executor.go
  backend/schedulerd/executor_test.go
  backend/schedulerd/interface.go
  backend/schedulerd/interval_scheduler.go
  backend/schedulerd/proxy_check.go
  backend/schedulerd/proxy_check_test.go
  backend/schedulerd/round_robin_scheduler.go
  backend/schedulerd/round_robin_scheduler_test.go
  backend/schedulerd/roundrobin_cron.go
  backend/schedulerd/roundrobin_interval.go
  backend/schedulerd/schedulerd.go
  backend/schedulerd/schedulerd_test.go
  backend/schedulerd/timeproxy_test.go
  backend/store/etcd/ring.go
  backend/store/etcd/watchers.go
  backend/store/store.go
  docker-compose.yaml
  testing/mockring/LICENSE
  testing/mockring/ring.go
  testing/mockstore/entities.go
Labels: ready-for-review

#2776 Fix round robin scheduling issue
  backend/ringv2/interface.go
  backend/ringv2/pool.go
  backend/ringv2/pool_test.go
  backend/ringv2/ringv2.go
  backend/ringv2/ringv2_test.go
  backend/schedulerd/entity_cache.go
  backend/schedulerd/roundrobin_cron.go
  backend/schedulerd/roundrobin_interval.go
Labels: ready-for-review

#2771 Update changelog for v5.3.0 release
  CHANGELOG.md
  CHANGELOGS/unreleased/2103-offline-state-detection.md
  CHANGELOGS/unreleased/2699-round-robin-scheduling.md
  CHANGELOGS/unreleased/2700-strengthen_TLS_security_posture.md
  CHANGELOGS/unreleased/2710-sensuctl_httpclient_timeout.md
  CHANGELOGS/unreleased/2735-entity-subscription-bugfix.md
  CHANGELOGS/unreleased/2745-bugfix_asset_fetcher.md
  CHANGELOGS/unreleased/2767-edition-header.md
Labels: ready-for-review

#2783 Don't store events with a zero timestamp
  CHANGELOGS/unreleased/2636-event-timestamp.md
  api/core/v2/event_test.go
  backend/store/etcd/event_store.go
  backend/store/etcd/event_store_test.go
Labels: ready-for-review

#2797 Update eslint-config-prettier to v4.1.0
  dashboard/.eslintrc.yml
  dashboard/package.json
  dashboard/yarn.lock
Labels: ready-for-review, web-ui

#2770 Fix issue causing global flags to be ignored
  CHANGELOGS/unreleased/2345-sensuctl_flag_ordering_flag_ignored.md
  Gopkg.lock
  Gopkg.toml
  cli/client/config/basic/basic.go
  cli/commands/asset/create.go
  cli/commands/hooks/ensure_configured.go
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/command.go
Labels: ready-for-review

#2817 [Web] Handle case where creator is inaccessible
  CHANGELOGS/unreleased/2817-creator-exception.md
  backend/apid/graphql/schema/silenced.gql.go
  backend/apid/graphql/schema/silenced.graphql
  dashboard/src/components/partials/ClearSilencedEntriesDialog/Dialog.js
  dashboard/src/components/partials/SilencesList/SilencesListItem.js
  dashboard/src/components/partials/TableToolbarCell/FloatingTableToolbarCell.js
Labels: bug, ready-for-review, web-ui

#2762 Sensuctl delete client should use generic functions, commands should load namespace
  CHANGELOGS/unreleased/2583-sensuctl_wont_delete.md
  backend/apid/graphql/mutations.go
  backend/apid/graphql/mutations_test.go
  cli/client/check.go
  cli/client/entity.go
  cli/client/event.go
  cli/client/filter.go
  cli/client/handler.go
  cli/client/hook.go
  cli/client/interface.go
  cli/client/mutator.go
  cli/client/namespace.go
  cli/client/path.go
  cli/client/role.go
  cli/client/rolebinding.go
  cli/client/silenced.go
  cli/client/testing/mock_check_client.go
  cli/client/testing/mock_entity_client.go
  cli/client/testing/mock_event_client.go
  cli/client/testing/mock_filter_client.go
  cli/client/testing/mock_handler_client.go
  cli/client/testing/mock_hook_client.go
  cli/client/testing/mock_mutator_client.go
  cli/client/testing/mock_role_client.go
  cli/client/testing/mock_rolebinding_client.go
  cli/client/testing/mock_silenced_client.go
  cli/commands/check/delete.go
  cli/commands/check/delete_test.go
  cli/commands/clusterrole/delete.go
  cli/commands/clusterrole/delete_test.go
  cli/commands/clusterrolebinding/delete.go
  cli/commands/clusterrolebinding/delete_test.go
  cli/commands/entity/delete.go
  cli/commands/entity/delete_test.go
  cli/commands/event/delete.go
  cli/commands/event/delete_test.go
  cli/commands/filter/delete.go
  cli/commands/filter/delete_test.go
  cli/commands/handler/delete.go
  cli/commands/handler/delete_test.go
  cli/commands/hook/delete.go
  cli/commands/hook/delete_test.go
  cli/commands/mutator/delete.go
  cli/commands/mutator/delete_test.go
  cli/commands/role/delete.go
  cli/commands/role/delete_test.go
  cli/commands/rolebinding/delete.go
  cli/commands/rolebinding/delete_test.go
  cli/commands/silenced/delete.go
  cli/commands/silenced/delete_test.go
Labels: ready-for-review

#2818 Implements tessen store and api
  CHANGELOGS/unreleased/2789-tessen-store.md
  CHANGELOGS/unreleased/2795-tessen-api.md
  api/core/v2/meta.pb.go
  api/core/v2/tessen.go
  api/core/v2/tessen.pb.go
  api/core/v2/tessen.proto
  api/core/v2/tessen_test.go
  api/core/v2/tessenpb_test.go
  api/core/v2/typemap.go
  api/core/v2/types_gen.go
  backend/apid/actions/tessen.go
  backend/apid/actions/tessen_test.go
  backend/apid/apid.go
  backend/apid/routers/tessen.go
  backend/apid/routers/tessen_test.go
  backend/store/etcd/tessen_store.go
  backend/store/etcd/tessen_store_test.go
  backend/store/store.go
  testing/mockstore/tessen.go
  types/aliases.go
  types/wrapper.go
Labels: ready-for-review

#2823 [Web] Update vulnerable dev packages
  CHANGELOGS/unreleased/2823-web-update-dev-packages.md
  dashboard/package.json
  dashboard/scripts/audit-deps.js
  dashboard/yarn.lock
Labels: web-ui

#2829 [Api] Return 404 when user is not found for given name
  CHANGELOG.md
  CHANGELOGS/unreleased/2829-fixup-find-user.md
  backend/apid/routers/users.go
  backend/apid/routers/users_test.go
Labels: bug, ready-for-review

#2827 Use contexts for cancellation
  CHANGELOGS/unreleased/2756-agent-cancellation.md
  agent/agent.go
  agent/agent_test.go
  agent/check_handler.go
  agent/check_handler_env_test_unix.go
  agent/check_handler_env_test_windows.go
  agent/check_handler_internal_test.go
  agent/cmd/start.go
  agent/config.go
  agent/sockets.go
  agent/sockets_test.go
  agent/statsd_server_test.go
  asset/asset.go
  asset/boltdb_manager.go
  asset/boltdb_manager_test.go
  asset/fetcher.go
  asset/fetcher_test.go
  asset/filtered_manager.go
  asset/filtered_manager_test.go
  asset/integration_test.go
  asset/manager.go
  asset/set.go
  asset/set_test.go
  backend/agentd/session.go
  backend/backend.go
  backend/pipelined/filter.go
  backend/pipelined/handle.go
  backend/pipelined/mutate.go
  benchmark/cmd/main.go
  handler/handler.go
  handler/handler_test.go
  util/retry/retry.go
Labels: ready-for-review

#2832 [Web UI] Set up consumable npm package
  dashboard/.babelrc
  dashboard/babel.config.js
  dashboard/config/app.webpack.config.js
  dashboard/config/base.webpack.config.js
  dashboard/config/lib.webpack.config.js
  dashboard/config/vendor.webpack.config.js
  dashboard/dashboard.tgz
  dashboard/package.json
  dashboard/scripts/serve.js
  dashboard/src/app/component/partial/SigninDialog/SigninDialog.js
Labels: ready-for-review

#2833 [Web UI] Update generated npm package tarball
  dashboard/dashboard.tgz
Labels: ready-for-review

#2722 closes #2642 separate TLS config for dashboard
  CHANGELOGS/unreleased/2722-seperate_TLS_config_for_dashboard.md
  backend/backend.go
  backend/cmd/start.go
  backend/config.go
Labels: ready-for-review

#2834 Fix UserController after pagination merge
  backend/apid/routers/users.go
  backend/apid/routers/users_test.go
Labels: ready-for-review

#2810 Instrument with Prometheus
  Gopkg.lock
  Gopkg.toml
  agent/api.go
  backend/apid/apid.go
  backend/eventd/eventd.go
  vendor/github.com/prometheus/client_golang/.gitignore
  vendor/github.com/prometheus/client_golang/.travis.yml
  vendor/github.com/prometheus/client_golang/CHANGELOG.md
  vendor/github.com/prometheus/client_golang/CONTRIBUTING.md
  vendor/github.com/prometheus/client_golang/README.md
  vendor/github.com/prometheus/client_golang/VERSION
  vendor/github.com/prometheus/client_golang/api/prometheus/api.go
  vendor/github.com/prometheus/client_golang/examples/random/main.go
  vendor/github.com/prometheus/client_golang/examples/simple/main.go
  vendor/github.com/prometheus/client_golang/prometheus/push/push.go
Labels: ready-for-review

#2837 [Web UI] Allow AppLayout component to be full width
  dashboard/src/lib/component/base/AppLayout/AppLayout.js
Labels: ready-for-review

#2835 Release 5.4.0
  CHANGELOG.md
  CHANGELOGS/unreleased/2345-sensuctl_flag_ordering_flag_ignored.md
  CHANGELOGS/unreleased/2583-sensuctl_wont_delete.md
  CHANGELOGS/unreleased/2604-api-pagination.md
  CHANGELOGS/unreleased/2636-event-timestamp.md
  CHANGELOGS/unreleased/2722-seperate_TLS_config_for_dashboard.md
  CHANGELOGS/unreleased/2743-dinnae-store-metrics.md
  CHANGELOGS/unreleased/2756-agent-cancellation.md
  CHANGELOGS/unreleased/2786-add-asset-collections.md
  CHANGELOGS/unreleased/2789-tessen-store.md
  CHANGELOGS/unreleased/2795-tessen-api.md
  CHANGELOGS/unreleased/2801-agent-api-queue.md
  CHANGELOGS/unreleased/2817-creator-exception.md
  CHANGELOGS/unreleased/2823-web-update-dev-packages.md
  CHANGELOGS/unreleased/2824-web-update-babel.md
  CHANGELOGS/unreleased/2825-update-ui-library.md
  CHANGELOGS/unreleased/2829-fixup-find-user.md
Labels: ready-for-review

#2820 Feature/tessen sensuctl
  CHANGELOGS/unreleased/2794-tessen-sensuctl.md
  cli/client/generic.go
  cli/client/interface.go
  cli/client/testing/mock_generic.go
  cli/commands/commands.go
  cli/commands/helpers/prompts.go
  cli/commands/tessen/help.go
  cli/commands/tessen/info.go
  cli/commands/tessen/info_test.go
  cli/commands/tessen/opt_in.go
  cli/commands/tessen/opt_in_test.go
  cli/commands/tessen/opt_out.go
  cli/commands/tessen/opt_out_test.go
  testing/mockstore/tessen.go
Labels: ready-for-review

#2842 Implement tessend and etcd watcher
  CHANGELOGS/unreleased/2791-tessen-daemon.md
  CHANGELOGS/unreleased/2792-tessen-etcd-watcher.md
  api/core/v2/tessen.go
  api/core/v2/tessen_test.go
  backend/apid/actions/tessen.go
  backend/apid/actions/tessen_test.go
  backend/apid/routers/tessen.go
  backend/apid/routers/tessen_test.go
  backend/backend.go
  backend/store/etcd/tessen_store.go
  backend/store/etcd/tessen_store_test.go
  backend/store/etcd/watchers.go
  backend/store/store.go
  backend/tessend/LICENSE
  backend/tessend/data.go
  backend/tessend/logger.go
  backend/tessend/tessend.go
  backend/tessend/tessend_test.go
  testing/mockstore/hook_config.go
  testing/mockstore/tessen.go
Labels: ready-for-review
