Repository sensu/sensu-go, pull requests merged in 2019-02, with the labels that each got.

#2673 Change /provider to /auth-provider
  backend/authentication/providers/basic/basic.go
Labels: ready-for-review

#2676 Add support for wrapped resources storage
  CHANGELOG.md
  api/core/v2/provider.go
  backend/apid/routers/authentication.go
  backend/apid/routers/authentication_test.go
  backend/authentication/authenticator.go
  backend/authentication/providers/basic/basic.go
  backend/backend.go
  backend/store/etcd/store.go
  cli/client/generic.go
  cli/client/interface.go
  cli/client/testing/mock_generic.go
  cli/commands/create/create.go
  cli/commands/edit/edit.go
Labels: ready-for-review

#2685 Ensure dead entities are buried when appropriate
  CHANGELOG.md
  backend/eventd/eventd.go
  backend/eventd/integration_test.go
  backend/keepalived/keepalived.go
  backend/liveness/liveness.go
  backend/liveness/liveness_test.go
Labels: ready-for-review

#2681 Fix copy displayed when disabling users with sensuctl
  CHANGELOG.md
  cli/commands/helpers/prompts.go
  cli/commands/user/delete.go
Labels: bug, ready-for-review, sensuctl

#2694 Use TLS client config when configuring GraphQL service
  backend/apid/apid.go
Labels: ready-for-review, regression

#2692 Update CHANGELOG.md for 5.2.0 release
  CHANGELOG.md
Labels: ready-for-review

#2703 release checkKey lock correctly
  CHANGELOG.md
  agent/check_handler.go
  agent/check_handler_internal_test.go
Labels: ready-for-review

#2706 Bump the changelog for the 5.2.1 release
  CHANGELOG.md
Labels: ready-for-review

#2702 Add handlers to v1.CheckResult
  CHANGELOG.md
  agent/agent.go
  agent/entity.go
  agent/entity_test.go
  agent/event.go
  agent/event_test.go
  agent/timeproxy_test.go
  api/core/v2/event.go
  types/v1/check.go
Labels: ready-for-review

#2710 Set sensuctl http client timeout to 15 seconds
  CHANGELOGS/unreleased/2710-sensuctl_httpclient_timeout.md
  cli/client/client.go
Labels: ready-for-review

#2700 closes #2657 - strengthen our TLS security posture
  .gitignore
  CHANGELOGS/unreleased/2700-strengthen_TLS_security_posture.md
  api/core/v2/tls.go
  backend/agentd/agentd.go
  backend/apid/apid.go
  backend/cmd/start.go
  backend/dashboardd/dashboardd.go
  backend/etcd/etcd.go
  transport/client.go
Labels: ready-for-review

#2684 [Web UI] Bump global polling interval
  dashboard/src/apollo/httpLink.js
  dashboard/src/components/views/EnvironmentView/CheckDetailsContent.js
  dashboard/src/components/views/EnvironmentView/ChecksContent.js
  dashboard/src/components/views/EnvironmentView/EntitiesContent.js
  dashboard/src/components/views/EnvironmentView/EntityDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
  dashboard/src/components/views/EnvironmentView/SilencesContent.js
  dashboard/src/constants/polling.js
Labels: ready-for-review, web-ui

#2725 Update the PR tempate with a more clear QA verification step
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-review

#2759 Update Go on AppVeyor to 1.11.5
  .appveyor.yml
Labels: ready-for-review
