Repository sensu/sensu-go, pull requests merged in 2019-10, with the labels that each got.

#3314 [GraphQL] Fixup entity object meta regression
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_test.go
  backend/apid/graphql/scalars.go
Labels: regression

#3277 Fix authorization of event & silence updates
  CHANGELOG.md
  backend/api/event.go
  backend/api/event_test.go
  backend/api/silenced.go
  backend/api/silenced_test.go
Labels: regression

#3315 [API] Configure generic client with properly formatted group
  CHANGELOG.md
  backend/api/generic.go
  backend/api/generic_test.go
Labels: bug

#3313 Implement a couple of Greg's TODOs
  agent/agent.go
  backend/agentd/session.go
Labels: low hanging :grapes:

#3358 [GraphQL] Expose service for upstream implementations
  backend/apid/apid.go
  backend/apid/graphql/service.go
  backend/apid/routers/graphql.go
  backend/apid/routers/graphql_test.go
  backend/backend.go
  go.mod
Labels: enhancement
