Repository sensu/sensu-go, pull requests merged in 2019-01, with the labels that each got.

#2587 Fix a bug in the check scheduler where a check would immediately fires if updated
  CHANGELOG.md
  backend/schedulerd/check_scheduler.go
  backend/schedulerd/check_scheduler_test.go
  backend/schedulerd/check_scheduler_unit_test.go
  backend/schedulerd/check_watcher.go
  backend/schedulerd/check_watcher_test.go
Labels: ready-for-review

#2577 Add package liveness
  backend/etcd/etcd.go
  backend/liveness/liveness.go
  backend/liveness/liveness_test.go
  backend/store/namespace.go
Labels: ready-for-review

#2591 Fixes a bug where a bad line in check output would abort metric extraction
  CHANGELOG.md
  agent/check_handler.go
  agent/transformers/graphite.go
  agent/transformers/graphite_test.go
  agent/transformers/influx_db.go
  agent/transformers/influx_db_test.go
  agent/transformers/logger.go
  agent/transformers/nagios.go
  agent/transformers/nagios_test.go
  agent/transformers/opentsdb.go
  agent/transformers/opentsdb_test.go
  agent/transformers/transformer.go
Labels: ready-for-review

#2278 API authentication credential test endpoint
  backend/apid/routers/authentication.go
  backend/apid/routers/authentication_test.go
  cli/client/authentication.go
  cli/client/interface.go
  cli/client/testing/mock_authentication_client.go
  cli/commands/user/help.go
  cli/commands/user/test-creds.go
  cli/commands/user/test-creds_test.go
Labels: ready-for-review, review

#2614 Update the PR template to include an acceptance test
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-review

#2464 Handle case where refresh token is no longer in allow list
  backend/apid/middlewares/allowlist.go
  backend/apid/middlewares/allowlist_test.go
  backend/apid/routers/authentication.go
  backend/store/etcd/token_store.go
Labels: ready-for-review

#2616 Add better error checking/handling to entity cli client
  CHANGELOG.md
  cli/client/entity.go
Labels: ready-for-review

#2603 Use Go 1.11 on CircleCI
  .circleci/config.yml
  build/ci/gofmt-linting-check.sh
Labels: ready-for-review

#2617 Add changelog entry for go version
  CHANGELOG.md
Labels: ready-for-review

#2610 Add Authentication Providers
  CHANGELOG.md
  api/core/v2/token.go
  api/core/v2/typemap.go
  backend/apid/apid.go
  backend/apid/middlewares/allowlist.go
  backend/apid/middlewares/allowlist_test.go
  backend/apid/middlewares/authentication_test.go
  backend/apid/middlewares/refresh_token_test.go
  backend/apid/routers/authentication.go
  backend/apid/routers/authentication_test.go
  backend/apid/routers/graphql.go
  backend/authentication/jwt/jwt.go
  backend/authentication/jwt/jwt_test.go
  backend/authentication/providers/LICENSE
  backend/authentication/providers/basic/LICENSE
  backend/authentication/providers/basic/basic.go
  backend/authentication/providers/logger.go
  backend/authentication/providers/providers.go
  backend/backend.go
  backend/daemon/daemon.go
  backend/store/etcd/token_store.go
  backend/store/etcd/token_store_test.go
  backend/store/etcd/user_store.go
  backend/store/etcd/user_store_test.go
  backend/store/store.go
  cli/commands/check/execute_test.go
  cli/commands/configure/configure.go
  testing/mockstore/token.go
Labels: ready-for-review

#2618 Generic store functions
  CHANGELOG.md
  backend/store/etcd/clusterrole_store.go
  backend/store/etcd/clusterrolebinding_store.go
  backend/store/etcd/role_store.go
  backend/store/etcd/rolebinding_store.go
  backend/store/etcd/store.go
  backend/store/etcd/store_test.go
Labels: ready-for-review

#2619 Increase parallelism and resource_class for build and test jobs in circle ci
  .circleci/config.yml
Labels: ready-for-review

#2601 Use package liveness in keepalived
  CHANGELOG.md
  agent/agent.go
  api/core/v2/check.go
  backend/backend.go
  backend/eventd/integration_test.go
  backend/keepalived/integration_test.go
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
  backend/liveness/liveness.go
  backend/liveness/liveness_test.go
Labels: ready-for-review

#2615 [Web UI] Updated toolbar and hover buttons for dark mode
  CHANGELOG.md
  dashboard/src/components/partials/EventsList/EventsListItem.js
  dashboard/src/components/partials/TableToolbarCell/FloatingTableToolbarCell.js
  dashboard/src/components/partials/TableToolbarCell/TableToolbarCell.js
  dashboard/src/components/partials/Toolbar/Toolbar.js
  dashboard/src/components/partials/ToolbarMenuItems/Button.js
Labels: ready-for-review

#2632 Update Changelog with 5.1.1 release
  CHANGELOG.md
Labels: ready-for-review

#2620 Removed unused workflow in CircleCI
  .circleci/config.yml
  CHANGELOG.md
Labels: ready-for-review

#2625 Fix a bug in proxy check execution
  CHANGELOG.md
  agent/check_handler.go
  agent/check_handler_internal_test.go
  agent/hook_test.go
  testing/mockexecutor/executor.go
Labels: ready-for-review

#2639 Add support for enterprise providers
  CHANGELOG.md
  api/core/v2/provider.go
  api/core/v2/token.go
  api/core/v2/typemap.go
  backend/apid/apid.go
  backend/apid/routers/authentication.go
  backend/apid/routers/authentication_test.go
  backend/authentication/LICENSE
  backend/authentication/authenticator.go
  backend/authentication/logger.go
  backend/authentication/providers/LICENSE
  backend/authentication/providers/basic/basic.go
  backend/authentication/providers/providers.go
  backend/backend.go
  backend/store/etcd/watcher.go
  backend/store/etcd/watcher_test.go
  backend/store/etcd/watchers.go
  backend/store/store.go
  backend/store/watcher.go
  scripts/make_typemap/make_typemap.go
  scripts/make_typemap/make_typemap_test.go
  testing/mockstore/assets.go
  types/wrapper.go
Labels: ready-for-review

#2648 Fix CI failure due to fpm installation
  build/ci/circle-ci-setup.sh
Labels: ready-for-review

#2627 Better TLS support for sensuctl
  CHANGELOG.md
  api/core/v2/tls.go
  backend/cmd/start.go
  backend/etcd/etcd.go
  cli/cli.go
  cli/client/config/basic/basic.go
  cli/commands/root/root.go
  transport/client.go
Labels: ready-for-review

#2640 [Web UI] add silence / unsilence to event details page
  CHANGELOG.md
  api/core/v2/event.go
  api/core/v2/event_test.go
  backend/apid/graphql/event.go
  backend/apid/graphql/event_test.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  backend/apid/graphql/schema/event.gql.go
  backend/apid/graphql/schema/event.graphql
  backend/apid/graphql/schema/silenced.gql.go
  backend/apid/graphql/schema/silenced.graphql
  backend/apid/graphql/service.go
  backend/eventd/silenced.go
  backend/eventd/silenced_test.go
  dashboard/src/apollo/schema/combined.graphql
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsClearSilenceAction.js
  dashboard/src/components/partials/CheckDetailsContainer/CheckDetailsToolbar.js
  dashboard/src/components/partials/ClearSilenceAction/ClearSilenceAction.js
  dashboard/src/components/partials/ClearSilenceAction/index.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsClearSilenceAction.js
  dashboard/src/components/partials/EntityDetailsContainer/EntityDetailsToolbar.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsCheckResult.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsContent.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSilenceAction.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsSummary.js
  dashboard/src/components/partials/EventDetailsContainer/EventDetailsToolbar.js
  dashboard/src/components/partials/EventsList/EventsList.js
  dashboard/src/components/partials/EventsList/EventsListHeader.js
  dashboard/src/components/views/EnvironmentView/EventDetailsContent.js
  dashboard/src/components/views/EnvironmentView/EventsContent.js
Labels: ready-for-review, web-ui

#2646 Omit substituted values command & check hook values
  CHANGELOG.md
  agent/check_handler.go
  agent/check_handler_env_test_unix.go
  agent/check_handler_env_test_windows.go
  agent/check_handler_internal_test.go
  agent/hook.go
Labels: 1.x parity, bug, ready-for-review, web-ui

#2645 Fix a bug in keepalived that could result in a crash
  CHANGELOG.md
  backend/keepalived/keepalived.go
  backend/keepalived/keepalived_test.go
Labels: ready-for-review

#2656 Remove travis badge
  README.md
Labels: ready-for-review

#2655 Replace FAQ contents with a link to official FAQ
  FAQ.md
Labels: ready-for-review

#2654 Remove .kitchen.yml
  .kitchen.yml
Labels: ready-for-review

#2653 Add support for check output truncation
  CHANGELOG.md
  agent/check_handler.go
  agent/check_handler_internal_test.go
  api/core/v2/check.go
  api/core/v2/check.pb.go
  api/core/v2/check.proto
  backend/store/etcd/event_store.go
  backend/store/etcd/event_store_test.go
  command/command.go
Labels: ready-for-review

#2661 Add support for enterprise sensuctl commands
  CHANGELOG.md
  api/core/v2/provider.go
  cli/client/cluster.go
  cli/client/clusterrole.go
  cli/client/clusterrolebinding.go
  cli/client/generic.go
  cli/client/interface.go
  cli/client/methods.go
  cli/client/namespace.go
  cli/client/path.go
  cli/client/role.go
  cli/client/rolebinding.go
  cli/client/testing/mock_generic.go
  cli/client/testing/mock_health_client.go
  cli/client/user.go
Labels: ready-for-review

#2672 Non-namespaced resources shouldn't return ErrNamespaceMissing
  CHANGELOG.md
  backend/store/etcd/store.go
  backend/store/etcd/store_test.go
Labels: ready-for-review
