Repository sensu/sensu-go, pull requests merged in 2019-05, with the labels that each got.

#2960 Fix Namespace and User pagination
  CHANGELOG.md
  backend/store/etcd/namespace_store_test.go
  backend/store/etcd/store.go
  backend/store/etcd/user_store_test.go
Labels: bug

#2951 [GraphQL] Implement simpler extensible filtering
  CHANGELOG.md
  backend/apid/graphql/check_filters.go
  backend/apid/graphql/check_filters_test.go
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_filters.go
  backend/apid/graphql/entity_filters_test.go
  backend/apid/graphql/event_filters.go
  backend/apid/graphql/event_filters_test.go
  backend/apid/graphql/filter/boolean.go
  backend/apid/graphql/filter/boolean_test.go
  backend/apid/graphql/filter/filter.go
  backend/apid/graphql/filter/filter_test.go
  backend/apid/graphql/filter/string.go
  backend/apid/graphql/filter/string_test.go
  backend/apid/graphql/global_filters.go
  backend/apid/graphql/handler_filters.go
  backend/apid/graphql/handler_filters_test.go
  backend/apid/graphql/namespace.go
  backend/apid/graphql/namespace_test.go
  backend/apid/graphql/schema/check.gql.go
  backend/apid/graphql/schema/check.graphql
  backend/apid/graphql/schema/entity.gql.go
  backend/apid/graphql/schema/entity.graphql
  backend/apid/graphql/schema/errors.gql.go
  backend/apid/graphql/schema/event.gql.go
  backend/apid/graphql/schema/event.graphql
  backend/apid/graphql/schema/handler.gql.go
  backend/apid/graphql/schema/handler.graphql
  backend/apid/graphql/schema/namespace.gql.go
  backend/apid/graphql/schema/namespace.graphql
  backend/apid/graphql/schema/silenced.gql.go
  backend/apid/graphql/schema/silenced.graphql
  backend/apid/graphql/silence_filters.go
  backend/apid/graphql/silence_filters_test.go
Labels: web-ui

#2986 [Web] G-Zip dashboard assets
  CHANGELOG.md
  backend/dashboardd/dashboardd.go
Labels: regression, web-ui

#2996 Update cli/client package so errors are consistent
  cli/client/asset.go
  cli/client/error.go
  cli/client/extension.go
  cli/client/filter.go
  cli/client/generic.go
  cli/client/handler.go
  cli/client/namespace.go
  cli/commands/create/create.go
Labels: sensuctl

#3005 [GraphQL] Ensure only events associated with an entity are returned
  backend/apid/graphql/entity.go
  backend/apid/graphql/entity_test.go
Labels: regression
