Repository sensu/sensu-go, pull requests merged in 2020-10, with the labels that each got.

#4038 [backend/api] fill created_by field
  backend/api/check.go
  backend/api/entity.go
  backend/api/event.go
  backend/api/generic.go
  backend/api/meta.go
  backend/api/namespace_test.go
  backend/api/silenced.go
Labels: bug

#4037 [GraphQL] Fix entity suggestions
  backend/apid/graphql/query.go
Labels: regression

#4052 Close asset resp body when done reading from it (#4026)
  CHANGELOG.md
  asset/fetcher.go
Labels: backport

#4053 Backport js vm fixes from 6.x to 5.21
  CHANGELOG.md
  js/js.go
  js/vm_cache.go
Labels: backport
