Repository sensu/sensu-go, pull requests merged in 2020-06, with the labels that each got.

#3780 [GraphQL] Fetch events in batches
  CHANGELOG.md
  backend/apid/graphql/dataloader.go
  backend/apid/graphql/dataloader_test.go
Labels: bug

#3833 Issue valid deregistration events
  CHANGELOG.md
  backend/keepalived/deregisterer.go
  backend/keepalived/deregisterer_test.go
Labels: component:pipeline

#3838 Return new expiry date when renewing an auth token pair
  backend/api/authentication.go
Labels: bug, component:api
