Repository sensu/sensu-go, pull requests merged in 2022-02, with the labels that each got.

#4601 [GraphQL] Bump events max fetch size to 50k
  backend/apid/graphql/namespace.go
Labels: component:web-ui

#4598 [GraphQL] Partial count field
  backend/apid/graphql/interfaces.go
  backend/apid/graphql/mock_test.go
  backend/apid/graphql/namespace.go
  backend/apid/graphql/namespace_test.go
  backend/apid/graphql/pagination.go
  backend/apid/graphql/schema/pagination.gql.go
  backend/apid/graphql/schema/pagination.graphql
  backend/apid/graphql/service.go
Labels: enhancement, component:web-ui

#4599 [GraphQL] Use a sliding chunk size
  backend/apid/graphql/namespace.go
Labels: enhancement, component:web-ui

#4489 Add staticcheck github action
  .github/workflows/golangci-lint.yml
  .github/workflows/static-check.yml
  .golangci.yml
  agent/statsd.go
  agent/statsd_server_solaris.go
  backend/apid/graphql/check.go
  backend/apid/graphql/entity_test.go
  backend/apid/graphql/filter/filter.go
  backend/apid/graphql/filter/filter_test.go
  backend/apid/graphql/mutator_test.go
  backend/cmd/init.go
  backend/keepalived/keepalived_test.go
  backend/pipeline/filter/legacy.go
  backend/pipeline/mutator/javascript.go
  backend/store/etag.go
  backend/store/etcd/namespace_store.go
  cli/client/authentication.go
  cli/cmdmanager/manager.go
  cli/commands/hook/interactive.go
  cli/commands/hooks/ensure_configured.go
  cli/commands/user/create.go
  staticcheck.conf
  util/environment/environment.go
Labels: engineering:in-progress

#4618 [GraphQL] Continue paging until requested slice has been satisfied
  CHANGELOG.md
  backend/apid/graphql/namespace.go
  backend/apid/graphql/namespace_test.go
Labels: bug, component:web-ui

#4630 [GraphQL] Collect error types in metrics
  backend/apid/graphql/service.go
  graphql/tracing/prometheus.go
  graphql/tracing/prometheus_test.go
Labels: enhancement

#4637 [GraphQL] Add suggestions for pipeline resources
  backend/apid/graphql/suggest.go
Labels: component:web-ui
